package fr.mcnanotech.kevin_68.nanotech_mod.main.world;

import java.util.Random;

import fr.mcnanotech.kevin_68.nanotech_mod.main.blocks.NanotechBlock;

import net.minecraft.block.Block;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

public class WorldModel5 extends WorldGenerator
{
	protected int[] GetValidSpawnBlocks()
	{
		return new int[] {Block.stone.blockID, Block.dirt.blockID, NanotechBlock.nanoGrass.blockID, Block.snow.blockID};
	}

	public boolean LocationIsValidSpawn(World world, int i, int j, int k)
	{
		int distanceToAir = 0;
		int checkID = world.getBlockId(i, j, k);

		while(checkID != 0)
		{
			distanceToAir++;
			checkID = world.getBlockId(i, j + distanceToAir, k);
		}

		if(distanceToAir > 3)
		{
			return false;
		}
		j += distanceToAir - 1;

		int blockID = world.getBlockId(i, j, k);
		int blockIDAbove = world.getBlockId(i, j + 1, k);
		int blockIDBelow = world.getBlockId(i, j - 1, k);
		for(int x : GetValidSpawnBlocks())
		{
			if(blockIDAbove != 0)
			{
				return false;
			}
			if(blockID == x)
			{
				return true;
			}
			else if(blockID == Block.snow.blockID && blockIDBelow == x)
			{
				return true;
			}
		}
		return false;
	}

	public WorldModel5()
	{}

	public boolean generate(World world, Random rand, int i, int y, int k)
	{
		if(!LocationIsValidSpawn(world, i, y, k) || !LocationIsValidSpawn(world, i + 6, y, k) || !LocationIsValidSpawn(world, i + 6, y, k + 6) || !LocationIsValidSpawn(world, i, y, k + 6))
		{
			return false;
		}
		int j = y - 4;

		world.setBlock(i + 0, j + 0, k + 0, Block.stone.blockID);
		world.setBlock(i + 0, j + 0, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 0, k + 2, Block.stone.blockID);
		world.setBlock(i + 0, j + 0, k + 3, Block.stone.blockID);
		world.setBlock(i + 0, j + 0, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 0, k + 5, Block.stone.blockID);
		world.setBlock(i + 0, j + 0, k + 6, Block.stone.blockID);
		world.setBlock(i + 0, j + 1, k + 0, Block.stone.blockID);
		world.setBlock(i + 0, j + 1, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 1, k + 2, Block.stone.blockID);
		world.setBlock(i + 0, j + 1, k + 3, Block.stone.blockID);
		world.setBlock(i + 0, j + 1, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 1, k + 5, Block.stone.blockID);
		world.setBlock(i + 0, j + 1, k + 6, Block.stone.blockID);
		world.setBlock(i + 0, j + 2, k + 0, Block.dirt.blockID);
		world.setBlock(i + 0, j + 2, k + 1, Block.dirt.blockID);
		world.setBlock(i + 0, j + 2, k + 2, Block.dirt.blockID);
		world.setBlock(i + 0, j + 2, k + 3, Block.dirt.blockID);
		world.setBlock(i + 0, j + 2, k + 4, Block.dirt.blockID);
		world.setBlock(i + 0, j + 2, k + 5, Block.dirt.blockID);
		world.setBlock(i + 0, j + 2, k + 6, Block.dirt.blockID);
		world.setBlock(i + 0, j + 3, k + 0, Block.dirt.blockID);
		world.setBlock(i + 0, j + 3, k + 1, Block.dirt.blockID);
		world.setBlock(i + 0, j + 3, k + 2, Block.dirt.blockID);
		world.setBlock(i + 0, j + 3, k + 3, Block.dirt.blockID);
		world.setBlock(i + 0, j + 3, k + 4, Block.dirt.blockID);
		world.setBlock(i + 0, j + 3, k + 5, Block.dirt.blockID);
		world.setBlock(i + 0, j + 3, k + 6, Block.dirt.blockID);
		world.setBlock(i + 0, j + 4, k + 0, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 0, j + 4, k + 1, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 0, j + 4, k + 2, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 0, j + 4, k + 3, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 0, j + 4, k + 4, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 0, j + 4, k + 5, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 0, j + 4, k + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 0, j + 5, k + 0, 0);
		world.setBlock(i + 0, j + 5, k + 1, 0);
		world.setBlock(i + 0, j + 5, k + 2, 0);
		world.setBlock(i + 0, j + 5, k + 3, 0);
		world.setBlock(i + 0, j + 5, k + 4, 0);
		world.setBlock(i + 0, j + 5, k + 5, 0);
		world.setBlock(i + 0, j + 5, k + 6, 0);
		world.setBlock(i + 0, j + 6, k + 0, 0);
		world.setBlock(i + 0, j + 6, k + 1, 0);
		world.setBlock(i + 0, j + 6, k + 2, 0);
		world.setBlock(i + 0, j + 6, k + 3, 0);
		world.setBlock(i + 0, j + 6, k + 4, 0);
		world.setBlock(i + 0, j + 6, k + 5, 0);
		world.setBlock(i + 0, j + 6, k + 6, 0);
		world.setBlock(i + 0, j + 7, k + 0, 0);
		world.setBlock(i + 0, j + 7, k + 1, 0);
		world.setBlock(i + 0, j + 7, k + 2, 0);
		world.setBlock(i + 0, j + 7, k + 3, 0);
		world.setBlock(i + 0, j + 7, k + 4, 0);
		world.setBlock(i + 0, j + 7, k + 5, 0);
		world.setBlock(i + 0, j + 7, k + 6, 0);
		world.setBlock(i + 0, j + 8, k + 0, 0);
		world.setBlock(i + 0, j + 8, k + 1, 0);
		world.setBlock(i + 0, j + 8, k + 2, 0);
		world.setBlock(i + 0, j + 8, k + 3, 0);
		world.setBlock(i + 0, j + 8, k + 4, 0);
		world.setBlock(i + 0, j + 8, k + 5, 0);
		world.setBlock(i + 0, j + 8, k + 6, 0);
		world.setBlock(i + 0, j + 9, k + 0, 0);
		world.setBlock(i + 0, j + 9, k + 1, 0);
		world.setBlock(i + 0, j + 9, k + 2, 0);
		world.setBlock(i + 0, j + 9, k + 3, 0);
		world.setBlock(i + 0, j + 9, k + 4, 0);
		world.setBlock(i + 0, j + 9, k + 5, 0);
		world.setBlock(i + 0, j + 9, k + 6, 0);
		world.setBlock(i + 0, j + 10, k + 0, 0);
		world.setBlock(i + 0, j + 10, k + 1, 0);
		world.setBlock(i + 0, j + 10, k + 2, 0);
		world.setBlock(i + 0, j + 10, k + 3, 0);
		world.setBlock(i + 0, j + 10, k + 4, 0);
		world.setBlock(i + 0, j + 10, k + 5, 0);
		world.setBlock(i + 0, j + 10, k + 6, 0);
		world.setBlock(i + 0, j + 11, k + 0, 0);
		world.setBlock(i + 0, j + 11, k + 1, 0);
		world.setBlock(i + 0, j + 11, k + 2, 0);
		world.setBlock(i + 0, j + 11, k + 3, 0);
		world.setBlock(i + 0, j + 11, k + 4, 0);
		world.setBlock(i + 0, j + 11, k + 5, 0);
		world.setBlock(i + 0, j + 11, k + 6, 0);
		world.setBlock(i + 0, j + 12, k + 0, 0);
		world.setBlock(i + 0, j + 12, k + 1, 0);
		world.setBlock(i + 0, j + 12, k + 2, 0);
		world.setBlock(i + 0, j + 12, k + 3, 0);
		world.setBlock(i + 0, j + 12, k + 4, 0);
		world.setBlock(i + 0, j + 12, k + 5, 0);
		world.setBlock(i + 0, j + 12, k + 6, 0);
		world.setBlock(i + 1, j + 0, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 0, k + 1, Block.stone.blockID);
		world.setBlock(i + 1, j + 0, k + 2, Block.stone.blockID);
		world.setBlock(i + 1, j + 0, k + 3, Block.stone.blockID);
		world.setBlock(i + 1, j + 0, k + 4, Block.stone.blockID);
		world.setBlock(i + 1, j + 0, k + 5, Block.stone.blockID);
		world.setBlock(i + 1, j + 0, k + 6, Block.stone.blockID);
		world.setBlock(i + 1, j + 1, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 1, k + 1, Block.stone.blockID);
		world.setBlock(i + 1, j + 1, k + 2, Block.stone.blockID);
		world.setBlock(i + 1, j + 1, k + 3, Block.stone.blockID);
		world.setBlock(i + 1, j + 1, k + 4, Block.stone.blockID);
		world.setBlock(i + 1, j + 1, k + 5, Block.stone.blockID);
		world.setBlock(i + 1, j + 1, k + 6, Block.stone.blockID);
		world.setBlock(i + 1, j + 2, k + 0, Block.dirt.blockID);
		world.setBlock(i + 1, j + 2, k + 1, Block.dirt.blockID);
		world.setBlock(i + 1, j + 2, k + 2, Block.dirt.blockID);
		world.setBlock(i + 1, j + 2, k + 3, Block.dirt.blockID);
		world.setBlock(i + 1, j + 2, k + 4, Block.dirt.blockID);
		world.setBlock(i + 1, j + 2, k + 5, Block.dirt.blockID);
		world.setBlock(i + 1, j + 2, k + 6, Block.dirt.blockID);
		world.setBlock(i + 1, j + 3, k + 0, Block.dirt.blockID);
		world.setBlock(i + 1, j + 3, k + 1, Block.dirt.blockID);
		world.setBlock(i + 1, j + 3, k + 2, NanotechBlock.nukeBuildingStairs.blockID, 4, 0);
		world.setBlock(i + 1, j + 3, k + 3, NanotechBlock.nukeBuildingStairs.blockID, 4, 0);
		world.setBlock(i + 1, j + 3, k + 4, NanotechBlock.nukeBuildingStairs.blockID, 4, 0);
		world.setBlock(i + 1, j + 3, k + 5, Block.dirt.blockID);
		world.setBlock(i + 1, j + 3, k + 6, Block.dirt.blockID);
		world.setBlock(i + 1, j + 4, k + 0, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 1, j + 4, k + 1, NanotechBlock.nukeBuildingBlock.blockID, 8, 0);
		world.setBlock(i + 1, j + 4, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 4, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 4, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 4, k + 5, NanotechBlock.nukeBuildingBlock.blockID, 7, 0);
		world.setBlock(i + 1, j + 4, k + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 1, j + 5, k + 0, 0);
		world.setBlock(i + 1, j + 5, k + 1, NanotechBlock.nukeBuildingBlock.blockID, 8, 0);
		world.setBlock(i + 1, j + 5, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 5, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 5, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 5, k + 5, NanotechBlock.nukeBuildingBlock.blockID, 7, 0);
		world.setBlock(i + 1, j + 5, k + 6, 0);
		world.setBlock(i + 1, j + 6, k + 0, 0);
		world.setBlock(i + 1, j + 6, k + 1, NanotechBlock.nukeBuildingBlock.blockID, 8, 0);
		world.setBlock(i + 1, j + 6, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 6, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 6, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 6, k + 5, NanotechBlock.nukeBuildingBlock.blockID, 7, 0);
		world.setBlock(i + 1, j + 6, k + 6, 0);
		world.setBlock(i + 1, j + 7, k + 0, 0);
		world.setBlock(i + 1, j + 7, k + 1, 0);
		world.setBlock(i + 1, j + 7, k + 2, NanotechBlock.nukeBuildingStairs.blockID);
		world.setBlock(i + 1, j + 7, k + 3, NanotechBlock.nukeBuildingStairs.blockID);
		world.setBlock(i + 1, j + 7, k + 4, NanotechBlock.nukeBuildingStairs.blockID);
		world.setBlock(i + 1, j + 7, k + 5, 0);
		world.setBlock(i + 1, j + 7, k + 6, 0);
		world.setBlock(i + 1, j + 8, k + 0, 0);
		world.setBlock(i + 1, j + 8, k + 1, 0);
		world.setBlock(i + 1, j + 8, k + 2, 0);
		world.setBlock(i + 1, j + 8, k + 3, NanotechBlock.nukeBuildingBlock.blockID, 3, 0);
		world.setBlock(i + 1, j + 8, k + 4, 0);
		world.setBlock(i + 1, j + 8, k + 5, 0);
		world.setBlock(i + 1, j + 8, k + 6, 0);
		world.setBlock(i + 1, j + 9, k + 0, 0);
		world.setBlock(i + 1, j + 9, k + 1, 0);
		world.setBlock(i + 1, j + 9, k + 2, 0);
		world.setBlock(i + 1, j + 9, k + 3, 0);
		world.setBlock(i + 1, j + 9, k + 4, 0);
		world.setBlock(i + 1, j + 9, k + 5, 0);
		world.setBlock(i + 1, j + 9, k + 6, 0);
		world.setBlock(i + 1, j + 10, k + 0, 0);
		world.setBlock(i + 1, j + 10, k + 1, 0);
		world.setBlock(i + 1, j + 10, k + 2, 0);
		world.setBlock(i + 1, j + 10, k + 3, 0);
		world.setBlock(i + 1, j + 10, k + 4, 0);
		world.setBlock(i + 1, j + 10, k + 5, 0);
		world.setBlock(i + 1, j + 10, k + 6, 0);
		world.setBlock(i + 1, j + 11, k + 0, 0);
		world.setBlock(i + 1, j + 11, k + 1, 0);
		world.setBlock(i + 1, j + 11, k + 2, 0);
		world.setBlock(i + 1, j + 11, k + 3, 0);
		world.setBlock(i + 1, j + 11, k + 4, 0);
		world.setBlock(i + 1, j + 11, k + 5, 0);
		world.setBlock(i + 1, j + 11, k + 6, 0);
		world.setBlock(i + 1, j + 12, k + 0, 0);
		world.setBlock(i + 1, j + 12, k + 1, NanotechBlock.nukeBuildingBlock.blockID, 8, 0);
		world.setBlock(i + 1, j + 12, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 12, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 12, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 1, j + 12, k + 5, NanotechBlock.nukeBuildingBlock.blockID, 7, 0);
		world.setBlock(i + 1, j + 12, k + 6, 0);
		world.setBlock(i + 2, j + 0, k + 0, Block.stone.blockID);
		world.setBlock(i + 2, j + 0, k + 1, Block.stone.blockID);
		world.setBlock(i + 2, j + 0, k + 2, Block.stone.blockID);
		world.setBlock(i + 2, j + 0, k + 3, Block.stone.blockID);
		world.setBlock(i + 2, j + 0, k + 4, Block.stone.blockID);
		world.setBlock(i + 2, j + 0, k + 5, Block.stone.blockID);
		world.setBlock(i + 2, j + 0, k + 6, Block.stone.blockID);
		world.setBlock(i + 2, j + 1, k + 0, Block.stone.blockID);
		world.setBlock(i + 2, j + 1, k + 1, Block.stone.blockID);
		world.setBlock(i + 2, j + 1, k + 2, Block.stone.blockID);
		world.setBlock(i + 2, j + 1, k + 3, NanotechBlock.nukeBuildingStairs.blockID, 4, 0);
		world.setBlock(i + 2, j + 1, k + 4, Block.stone.blockID);
		world.setBlock(i + 2, j + 1, k + 5, Block.stone.blockID);
		world.setBlock(i + 2, j + 1, k + 6, Block.stone.blockID);
		world.setBlock(i + 2, j + 2, k + 0, Block.dirt.blockID);
		world.setBlock(i + 2, j + 2, k + 1, Block.dirt.blockID);
		world.setBlock(i + 2, j + 2, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 2, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 2, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 2, k + 5, Block.dirt.blockID);
		world.setBlock(i + 2, j + 2, k + 6, Block.dirt.blockID);
		world.setBlock(i + 2, j + 3, k + 0, Block.dirt.blockID);
		world.setBlock(i + 2, j + 3, k + 1, NanotechBlock.nukeBuildingStairs.blockID, 6, 0);
		world.setBlock(i + 2, j + 3, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 3, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 3, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 3, k + 5, NanotechBlock.nukeBuildingStairs.blockID, 7, 0);
		world.setBlock(i + 2, j + 3, k + 6, Block.dirt.blockID);
		world.setBlock(i + 2, j + 4, k + 0, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 2, j + 4, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 4, k + 2, Block.tnt.blockID);
		world.setBlock(i + 2, j + 4, k + 3, Block.tnt.blockID);
		world.setBlock(i + 2, j + 4, k + 4, Block.tnt.blockID);
		world.setBlock(i + 2, j + 4, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 4, k + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 2, j + 5, k + 0, 0);
		world.setBlock(i + 2, j + 5, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 5, k + 2, Block.tnt.blockID);
		world.setBlock(i + 2, j + 5, k + 3, Block.tnt.blockID);
		world.setBlock(i + 2, j + 5, k + 4, Block.tnt.blockID);
		world.setBlock(i + 2, j + 5, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 5, k + 6, 0);
		world.setBlock(i + 2, j + 6, k + 0, 0);
		world.setBlock(i + 2, j + 6, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 6, k + 2, Block.tnt.blockID);
		world.setBlock(i + 2, j + 6, k + 3, Block.tnt.blockID);
		world.setBlock(i + 2, j + 6, k + 4, Block.tnt.blockID);
		world.setBlock(i + 2, j + 6, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 6, k + 6, 0);
		world.setBlock(i + 2, j + 7, k + 0, 0);
		world.setBlock(i + 2, j + 7, k + 1, NanotechBlock.nukeBuildingStairs.blockID, 2, 0);
		world.setBlock(i + 2, j + 7, k + 2, Block.tnt.blockID);
		world.setBlock(i + 2, j + 7, k + 3, Block.tnt.blockID);
		world.setBlock(i + 2, j + 7, k + 4, Block.tnt.blockID);
		world.setBlock(i + 2, j + 7, k + 5, NanotechBlock.nukeBuildingStairs.blockID, 3, 0);
		world.setBlock(i + 2, j + 7, k + 6, 0);
		world.setBlock(i + 2, j + 8, k + 0, 0);
		world.setBlock(i + 2, j + 8, k + 1, 0);
		world.setBlock(i + 2, j + 8, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 8, k + 3, Block.tnt.blockID);
		world.setBlock(i + 2, j + 8, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 8, k + 5, 0);
		world.setBlock(i + 2, j + 8, k + 6, 0);
		world.setBlock(i + 2, j + 9, k + 0, 0);
		world.setBlock(i + 2, j + 9, k + 1, 0);
		world.setBlock(i + 2, j + 9, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 9, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 9, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 9, k + 5, 0);
		world.setBlock(i + 2, j + 9, k + 6, 0);
		world.setBlock(i + 2, j + 10, k + 0, 0);
		world.setBlock(i + 2, j + 10, k + 1, 0);
		world.setBlock(i + 2, j + 10, k + 2, 0);
		world.setBlock(i + 2, j + 10, k + 3, NanotechBlock.nukeBuildingStairs.blockID);
		world.setBlock(i + 2, j + 10, k + 4, 0);
		world.setBlock(i + 2, j + 10, k + 5, 0);
		world.setBlock(i + 2, j + 10, k + 6, 0);
		world.setBlock(i + 2, j + 11, k + 0, 0);
		world.setBlock(i + 2, j + 11, k + 1, 0);
		world.setBlock(i + 2, j + 11, k + 2, 0);
		world.setBlock(i + 2, j + 11, k + 3, 0);
		world.setBlock(i + 2, j + 11, k + 4, 0);
		world.setBlock(i + 2, j + 11, k + 5, 0);
		world.setBlock(i + 2, j + 11, k + 6, 0);
		world.setBlock(i + 2, j + 12, k + 0, 0);
		world.setBlock(i + 2, j + 12, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 12, k + 2, NanotechBlock.nukeBuildingBlock.blockID, 5, 0);
		world.setBlock(i + 2, j + 12, k + 3, NanotechBlock.nukeBuildingStairs.blockID, 1, 0);
		world.setBlock(i + 2, j + 12, k + 4, NanotechBlock.nukeBuildingBlock.blockID, 6, 0);
		world.setBlock(i + 2, j + 12, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 2, j + 12, k + 6, 0);
		world.setBlock(i + 3, j + 0, k + 0, Block.stone.blockID);
		world.setBlock(i + 3, j + 0, k + 1, Block.stone.blockID);
		world.setBlock(i + 3, j + 0, k + 2, Block.stone.blockID);
		world.setBlock(i + 3, j + 0, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 0, k + 4, Block.stone.blockID);
		world.setBlock(i + 3, j + 0, k + 5, Block.stone.blockID);
		world.setBlock(i + 3, j + 0, k + 6, Block.stone.blockID);
		world.setBlock(i + 3, j + 1, k + 0, Block.stone.blockID);
		world.setBlock(i + 3, j + 1, k + 1, Block.stone.blockID);
		world.setBlock(i + 3, j + 1, k + 2, NanotechBlock.nukeBuildingStairs.blockID, 6, 0);
		world.setBlock(i + 3, j + 1, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 1, k + 4, NanotechBlock.nukeBuildingStairs.blockID, 7, 0);
		world.setBlock(i + 3, j + 1, k + 5, Block.stone.blockID);
		world.setBlock(i + 3, j + 1, k + 6, Block.stone.blockID);
		world.setBlock(i + 3, j + 2, k + 0, Block.dirt.blockID);
		world.setBlock(i + 3, j + 2, k + 1, Block.dirt.blockID);
		world.setBlock(i + 3, j + 2, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 2, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 2, k + 5, Block.dirt.blockID);
		world.setBlock(i + 3, j + 2, k + 6, Block.dirt.blockID);
		world.setBlock(i + 3, j + 3, k + 0, Block.dirt.blockID);
		world.setBlock(i + 3, j + 3, k + 1, NanotechBlock.nukeBuildingStairs.blockID, 6, 0);
		world.setBlock(i + 3, j + 3, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 3, k + 3, Block.oreDiamond.blockID);
		world.setBlock(i + 3, j + 3, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 3, k + 5, NanotechBlock.nukeBuildingStairs.blockID, 7, 0);
		world.setBlock(i + 3, j + 3, k + 6, Block.dirt.blockID);
		world.setBlock(i + 3, j + 4, k + 0, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 3, j + 4, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 4, k + 2, Block.tnt.blockID);
		world.setBlock(i + 3, j + 4, k + 3, Block.tnt.blockID);
		world.setBlock(i + 3, j + 4, k + 4, Block.tnt.blockID);
		world.setBlock(i + 3, j + 4, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 4, k + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 3, j + 5, k + 0, 0);
		world.setBlock(i + 3, j + 5, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 5, k + 2, Block.tnt.blockID);
		world.setBlock(i + 3, j + 5, k + 3, Block.tnt.blockID);
		world.setBlock(i + 3, j + 5, k + 4, Block.tnt.blockID);
		world.setBlock(i + 3, j + 5, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 5, k + 6, 0);
		world.setBlock(i + 3, j + 6, k + 0, 0);
		world.setBlock(i + 3, j + 6, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 6, k + 2, Block.tnt.blockID);
		world.setBlock(i + 3, j + 6, k + 3, Block.tnt.blockID);
		world.setBlock(i + 3, j + 6, k + 4, Block.tnt.blockID);
		world.setBlock(i + 3, j + 6, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 6, k + 6, 0);
		world.setBlock(i + 3, j + 7, k + 0, 0);
		world.setBlock(i + 3, j + 7, k + 1, NanotechBlock.nukeBuildingStairs.blockID, 2, 0);
		world.setBlock(i + 3, j + 7, k + 2, Block.tnt.blockID);
		world.setBlock(i + 3, j + 7, k + 3, Block.tnt.blockID);
		world.setBlock(i + 3, j + 7, k + 4, Block.tnt.blockID);
		world.setBlock(i + 3, j + 7, k + 5, NanotechBlock.nukeBuildingStairs.blockID, 3, 0);
		world.setBlock(i + 3, j + 7, k + 6, 0);
		world.setBlock(i + 3, j + 8, k + 0, 0);
		world.setBlock(i + 3, j + 8, k + 1, NanotechBlock.nukeBuildingBlock.blockID, 4, 0);
		world.setBlock(i + 3, j + 8, k + 2, Block.tnt.blockID);
		world.setBlock(i + 3, j + 8, k + 3, Block.tnt.blockID);
		world.setBlock(i + 3, j + 8, k + 4, Block.tnt.blockID);
		world.setBlock(i + 3, j + 8, k + 5, NanotechBlock.nukeBuildingBlock.blockID, 2, 0);
		world.setBlock(i + 3, j + 8, k + 6, 0);
		world.setBlock(i + 3, j + 9, k + 0, 0);
		world.setBlock(i + 3, j + 9, k + 1, 0);
		world.setBlock(i + 3, j + 9, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 9, k + 3, Block.tnt.blockID);
		world.setBlock(i + 3, j + 9, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 9, k + 5, 0);
		world.setBlock(i + 3, j + 9, k + 6, 0);
		world.setBlock(i + 3, j + 10, k + 0, 0);
		world.setBlock(i + 3, j + 10, k + 1, 0);
		world.setBlock(i + 3, j + 10, k + 2, NanotechBlock.nukeBuildingStairs.blockID, 2, 0);
		world.setBlock(i + 3, j + 10, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 10, k + 4, NanotechBlock.nukeBuildingStairs.blockID, 3, 0);
		world.setBlock(i + 3, j + 10, k + 5, 0);
		world.setBlock(i + 3, j + 10, k + 6, 0);
		world.setBlock(i + 3, j + 11, k + 0, 0);
		world.setBlock(i + 3, j + 11, k + 1, 0);
		world.setBlock(i + 3, j + 11, k + 2, 0);
		world.setBlock(i + 3, j + 11, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 11, k + 4, 0);
		world.setBlock(i + 3, j + 11, k + 5, 0);
		world.setBlock(i + 3, j + 11, k + 6, 0);
		world.setBlock(i + 3, j + 12, k + 0, 0);
		world.setBlock(i + 3, j + 12, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 12, k + 2, NanotechBlock.nukeBuildingStairs.blockID, 3, 0);
		world.setBlock(i + 3, j + 12, k + 3, 0);
		world.setBlock(i + 3, j + 12, k + 4, NanotechBlock.nukeBuildingStairs.blockID, 2, 0);
		world.setBlock(i + 3, j + 12, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 3, j + 12, k + 6, 0);
		world.setBlock(i + 4, j + 0, k + 0, Block.stone.blockID);
		world.setBlock(i + 4, j + 0, k + 1, Block.stone.blockID);
		world.setBlock(i + 4, j + 0, k + 2, Block.stone.blockID);
		world.setBlock(i + 4, j + 0, k + 3, Block.stone.blockID);
		world.setBlock(i + 4, j + 0, k + 4, Block.stone.blockID);
		world.setBlock(i + 4, j + 0, k + 5, Block.stone.blockID);
		world.setBlock(i + 4, j + 0, k + 6, Block.stone.blockID);
		world.setBlock(i + 4, j + 1, k + 0, Block.stone.blockID);
		world.setBlock(i + 4, j + 1, k + 1, Block.stone.blockID);
		world.setBlock(i + 4, j + 1, k + 2, Block.stone.blockID);
		world.setBlock(i + 4, j + 1, k + 3, NanotechBlock.nukeBuildingStairs.blockID, 5, 0);
		world.setBlock(i + 4, j + 1, k + 4, Block.stone.blockID);
		world.setBlock(i + 4, j + 1, k + 5, Block.stone.blockID);
		world.setBlock(i + 4, j + 1, k + 6, Block.stone.blockID);
		world.setBlock(i + 4, j + 2, k + 0, Block.dirt.blockID);
		world.setBlock(i + 4, j + 2, k + 1, Block.dirt.blockID);
		world.setBlock(i + 4, j + 2, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 2, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 2, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 2, k + 5, Block.dirt.blockID);
		world.setBlock(i + 4, j + 2, k + 6, Block.dirt.blockID);
		world.setBlock(i + 4, j + 3, k + 0, Block.dirt.blockID);
		world.setBlock(i + 4, j + 3, k + 1, NanotechBlock.nukeBuildingStairs.blockID, 6, 0);
		world.setBlock(i + 4, j + 3, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 3, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 3, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 3, k + 5, NanotechBlock.nukeBuildingStairs.blockID, 7, 0);
		world.setBlock(i + 4, j + 3, k + 6, Block.dirt.blockID);
		world.setBlock(i + 4, j + 4, k + 0, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 4, j + 4, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 4, k + 2, Block.tnt.blockID);
		world.setBlock(i + 4, j + 4, k + 3, Block.tnt.blockID);
		world.setBlock(i + 4, j + 4, k + 4, Block.tnt.blockID);
		world.setBlock(i + 4, j + 4, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 4, k + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 4, j + 5, k + 0, 0);
		world.setBlock(i + 4, j + 5, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 5, k + 2, Block.tnt.blockID);
		world.setBlock(i + 4, j + 5, k + 3, Block.tnt.blockID);
		world.setBlock(i + 4, j + 5, k + 4, Block.tnt.blockID);
		world.setBlock(i + 4, j + 5, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 5, k + 6, 0);
		world.setBlock(i + 4, j + 6, k + 0, 0);
		world.setBlock(i + 4, j + 6, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 6, k + 2, Block.tnt.blockID);
		world.setBlock(i + 4, j + 6, k + 3, Block.tnt.blockID);
		world.setBlock(i + 4, j + 6, k + 4, Block.tnt.blockID);
		world.setBlock(i + 4, j + 6, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 6, k + 6, 0);
		world.setBlock(i + 4, j + 7, k + 0, 0);
		world.setBlock(i + 4, j + 7, k + 1, NanotechBlock.nukeBuildingStairs.blockID, 2, 0);
		world.setBlock(i + 4, j + 7, k + 2, Block.tnt.blockID);
		world.setBlock(i + 4, j + 7, k + 3, Block.tnt.blockID);
		world.setBlock(i + 4, j + 7, k + 4, Block.tnt.blockID);
		world.setBlock(i + 4, j + 7, k + 5, NanotechBlock.nukeBuildingStairs.blockID, 3, 0);
		world.setBlock(i + 4, j + 7, k + 6, 0);
		world.setBlock(i + 4, j + 8, k + 0, 0);
		world.setBlock(i + 4, j + 8, k + 1, 0);
		world.setBlock(i + 4, j + 8, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 8, k + 3, Block.tnt.blockID);
		world.setBlock(i + 4, j + 8, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 8, k + 5, 0);
		world.setBlock(i + 4, j + 8, k + 6, 0);
		world.setBlock(i + 4, j + 9, k + 0, 0);
		world.setBlock(i + 4, j + 9, k + 1, 0);
		world.setBlock(i + 4, j + 9, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 9, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 9, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 9, k + 5, 0);
		world.setBlock(i + 4, j + 9, k + 6, 0);
		world.setBlock(i + 4, j + 10, k + 0, 0);
		world.setBlock(i + 4, j + 10, k + 1, 0);
		world.setBlock(i + 4, j + 10, k + 2, 0);
		world.setBlock(i + 4, j + 10, k + 3, NanotechBlock.nukeBuildingStairs.blockID, 1, 0);
		world.setBlock(i + 4, j + 10, k + 4, 0);
		world.setBlock(i + 4, j + 10, k + 5, 0);
		world.setBlock(i + 4, j + 10, k + 6, 0);
		world.setBlock(i + 4, j + 11, k + 0, 0);
		world.setBlock(i + 4, j + 11, k + 1, 0);
		world.setBlock(i + 4, j + 11, k + 2, 0);
		world.setBlock(i + 4, j + 11, k + 3, 0);
		world.setBlock(i + 4, j + 11, k + 4, 0);
		world.setBlock(i + 4, j + 11, k + 5, 0);
		world.setBlock(i + 4, j + 11, k + 6, 0);
		world.setBlock(i + 4, j + 12, k + 0, 0);
		world.setBlock(i + 4, j + 12, k + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 12, k + 2, NanotechBlock.nukeBuildingBlock.blockID, 7, 0);
		world.setBlock(i + 4, j + 12, k + 3, NanotechBlock.nukeBuildingStairs.blockID);
		world.setBlock(i + 4, j + 12, k + 4, NanotechBlock.nukeBuildingBlock.blockID, 8, 0);
		world.setBlock(i + 4, j + 12, k + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 4, j + 12, k + 6, 0);
		world.setBlock(i + 5, j + 0, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 0, k + 1, Block.stone.blockID);
		world.setBlock(i + 5, j + 0, k + 2, Block.stone.blockID);
		world.setBlock(i + 5, j + 0, k + 3, Block.stone.blockID);
		world.setBlock(i + 5, j + 0, k + 4, Block.stone.blockID);
		world.setBlock(i + 5, j + 0, k + 5, Block.stone.blockID);
		world.setBlock(i + 5, j + 0, k + 6, Block.stone.blockID);
		world.setBlock(i + 5, j + 1, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 1, k + 1, Block.stone.blockID);
		world.setBlock(i + 5, j + 1, k + 2, Block.stone.blockID);
		world.setBlock(i + 5, j + 1, k + 3, Block.stone.blockID);
		world.setBlock(i + 5, j + 1, k + 4, Block.stone.blockID);
		world.setBlock(i + 5, j + 1, k + 5, Block.stone.blockID);
		world.setBlock(i + 5, j + 1, k + 6, Block.stone.blockID);
		world.setBlock(i + 5, j + 2, k + 0, Block.dirt.blockID);
		world.setBlock(i + 5, j + 2, k + 1, Block.dirt.blockID);
		world.setBlock(i + 5, j + 2, k + 2, Block.dirt.blockID);
		world.setBlock(i + 5, j + 2, k + 3, Block.dirt.blockID);
		world.setBlock(i + 5, j + 2, k + 4, Block.dirt.blockID);
		world.setBlock(i + 5, j + 2, k + 5, Block.dirt.blockID);
		world.setBlock(i + 5, j + 2, k + 6, Block.dirt.blockID);
		world.setBlock(i + 5, j + 3, k + 0, Block.dirt.blockID);
		world.setBlock(i + 5, j + 3, k + 1, Block.dirt.blockID);
		world.setBlock(i + 5, j + 3, k + 2, NanotechBlock.nukeBuildingStairs.blockID, 5, 0);
		world.setBlock(i + 5, j + 3, k + 3, NanotechBlock.nukeBuildingStairs.blockID, 5, 0);
		world.setBlock(i + 5, j + 3, k + 4, NanotechBlock.nukeBuildingStairs.blockID, 5, 0);
		world.setBlock(i + 5, j + 3, k + 5, Block.dirt.blockID);
		world.setBlock(i + 5, j + 3, k + 6, Block.dirt.blockID);
		world.setBlock(i + 5, j + 4, k + 0, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 5, j + 4, k + 1, NanotechBlock.nukeBuildingBlock.blockID, 6, 0);
		world.setBlock(i + 5, j + 4, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 4, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 4, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 4, k + 5, NanotechBlock.nukeBuildingBlock.blockID, 5, 0);
		world.setBlock(i + 5, j + 4, k + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 5, j + 5, k + 0, 0);
		world.setBlock(i + 5, j + 5, k + 1, NanotechBlock.nukeBuildingBlock.blockID, 6, 0);
		world.setBlock(i + 5, j + 5, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 5, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 5, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 5, k + 5, NanotechBlock.nukeBuildingBlock.blockID, 5, 0);
		world.setBlock(i + 5, j + 5, k + 6, 0);
		world.setBlock(i + 5, j + 6, k + 0, 0);
		world.setBlock(i + 5, j + 6, k + 1, NanotechBlock.nukeBuildingBlock.blockID, 6, 0);
		world.setBlock(i + 5, j + 6, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 6, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 6, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 6, k + 5, NanotechBlock.nukeBuildingBlock.blockID, 5, 0);
		world.setBlock(i + 5, j + 6, k + 6, 0);
		world.setBlock(i + 5, j + 7, k + 0, 0);
		world.setBlock(i + 5, j + 7, k + 1, 0);
		world.setBlock(i + 5, j + 7, k + 2, NanotechBlock.nukeBuildingStairs.blockID, 1, 0);
		world.setBlock(i + 5, j + 7, k + 3, NanotechBlock.nukeBuildingStairs.blockID, 1, 0);
		world.setBlock(i + 5, j + 7, k + 4, NanotechBlock.nukeBuildingStairs.blockID, 1, 0);
		world.setBlock(i + 5, j + 7, k + 5, 0);
		world.setBlock(i + 5, j + 7, k + 6, 0);
		world.setBlock(i + 5, j + 8, k + 0, 0);
		world.setBlock(i + 5, j + 8, k + 1, 0);
		world.setBlock(i + 5, j + 8, k + 2, 0);
		world.setBlock(i + 5, j + 8, k + 3, NanotechBlock.nukeBuildingBlock.blockID, 1, 0);
		world.setBlock(i + 5, j + 8, k + 4, 0);
		world.setBlock(i + 5, j + 8, k + 5, 0);
		world.setBlock(i + 5, j + 8, k + 6, 0);
		world.setBlock(i + 5, j + 9, k + 0, 0);
		world.setBlock(i + 5, j + 9, k + 1, 0);
		world.setBlock(i + 5, j + 9, k + 2, 0);
		world.setBlock(i + 5, j + 9, k + 3, 0);
		world.setBlock(i + 5, j + 9, k + 4, 0);
		world.setBlock(i + 5, j + 9, k + 5, 0);
		world.setBlock(i + 5, j + 9, k + 6, 0);
		world.setBlock(i + 5, j + 10, k + 0, 0);
		world.setBlock(i + 5, j + 10, k + 1, 0);
		world.setBlock(i + 5, j + 10, k + 2, 0);
		world.setBlock(i + 5, j + 10, k + 3, 0);
		world.setBlock(i + 5, j + 10, k + 4, 0);
		world.setBlock(i + 5, j + 10, k + 5, 0);
		world.setBlock(i + 5, j + 10, k + 6, 0);
		world.setBlock(i + 5, j + 11, k + 0, 0);
		world.setBlock(i + 5, j + 11, k + 1, 0);
		world.setBlock(i + 5, j + 11, k + 2, 0);
		world.setBlock(i + 5, j + 11, k + 3, 0);
		world.setBlock(i + 5, j + 11, k + 4, 0);
		world.setBlock(i + 5, j + 11, k + 5, 0);
		world.setBlock(i + 5, j + 11, k + 6, 0);
		world.setBlock(i + 5, j + 12, k + 0, 0);
		world.setBlock(i + 5, j + 12, k + 1, NanotechBlock.nukeBuildingBlock.blockID, 6, 0);
		world.setBlock(i + 5, j + 12, k + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 12, k + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 12, k + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(i + 5, j + 12, k + 5, NanotechBlock.nukeBuildingBlock.blockID, 5, 0);
		world.setBlock(i + 5, j + 12, k + 6, 0);
		world.setBlock(i + 6, j + 0, k + 0, Block.stone.blockID);
		world.setBlock(i + 6, j + 0, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 0, k + 2, Block.stone.blockID);
		world.setBlock(i + 6, j + 0, k + 3, Block.stone.blockID);
		world.setBlock(i + 6, j + 0, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 0, k + 5, Block.stone.blockID);
		world.setBlock(i + 6, j + 0, k + 6, Block.stone.blockID);
		world.setBlock(i + 6, j + 1, k + 0, Block.stone.blockID);
		world.setBlock(i + 6, j + 1, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 1, k + 2, Block.stone.blockID);
		world.setBlock(i + 6, j + 1, k + 3, Block.stone.blockID);
		world.setBlock(i + 6, j + 1, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 1, k + 5, Block.stone.blockID);
		world.setBlock(i + 6, j + 1, k + 6, Block.stone.blockID);
		world.setBlock(i + 6, j + 2, k + 0, Block.dirt.blockID);
		world.setBlock(i + 6, j + 2, k + 1, Block.dirt.blockID);
		world.setBlock(i + 6, j + 2, k + 2, Block.dirt.blockID);
		world.setBlock(i + 6, j + 2, k + 3, Block.dirt.blockID);
		world.setBlock(i + 6, j + 2, k + 4, Block.dirt.blockID);
		world.setBlock(i + 6, j + 2, k + 5, Block.dirt.blockID);
		world.setBlock(i + 6, j + 2, k + 6, Block.dirt.blockID);
		world.setBlock(i + 6, j + 3, k + 0, Block.dirt.blockID);
		world.setBlock(i + 6, j + 3, k + 1, Block.dirt.blockID);
		world.setBlock(i + 6, j + 3, k + 2, Block.dirt.blockID);
		world.setBlock(i + 6, j + 3, k + 3, Block.dirt.blockID);
		world.setBlock(i + 6, j + 3, k + 4, Block.dirt.blockID);
		world.setBlock(i + 6, j + 3, k + 5, Block.dirt.blockID);
		world.setBlock(i + 6, j + 3, k + 6, Block.dirt.blockID);
		world.setBlock(i + 6, j + 4, k + 0, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 6, j + 4, k + 1, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 6, j + 4, k + 2, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 6, j + 4, k + 3, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 6, j + 4, k + 4, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 6, j + 4, k + 5, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 6, j + 4, k + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(i + 6, j + 5, k + 0, 0);
		world.setBlock(i + 6, j + 5, k + 1, 0);
		world.setBlock(i + 6, j + 5, k + 2, 0);
		world.setBlock(i + 6, j + 5, k + 3, 0);
		world.setBlock(i + 6, j + 5, k + 4, 0);
		world.setBlock(i + 6, j + 5, k + 5, 0);
		world.setBlock(i + 6, j + 5, k + 6, 0);
		world.setBlock(i + 6, j + 6, k + 0, 0);
		world.setBlock(i + 6, j + 6, k + 1, 0);
		world.setBlock(i + 6, j + 6, k + 2, 0);
		world.setBlock(i + 6, j + 6, k + 3, 0);
		world.setBlock(i + 6, j + 6, k + 4, 0);
		world.setBlock(i + 6, j + 6, k + 5, 0);
		world.setBlock(i + 6, j + 6, k + 6, 0);
		world.setBlock(i + 6, j + 7, k + 0, 0);
		world.setBlock(i + 6, j + 7, k + 1, 0);
		world.setBlock(i + 6, j + 7, k + 2, 0);
		world.setBlock(i + 6, j + 7, k + 3, 0);
		world.setBlock(i + 6, j + 7, k + 4, 0);
		world.setBlock(i + 6, j + 7, k + 5, 0);
		world.setBlock(i + 6, j + 7, k + 6, 0);
		world.setBlock(i + 6, j + 8, k + 0, 0);
		world.setBlock(i + 6, j + 8, k + 1, 0);
		world.setBlock(i + 6, j + 8, k + 2, 0);
		world.setBlock(i + 6, j + 8, k + 3, 0);
		world.setBlock(i + 6, j + 8, k + 4, 0);
		world.setBlock(i + 6, j + 8, k + 5, 0);
		world.setBlock(i + 6, j + 8, k + 6, 0);
		world.setBlock(i + 6, j + 9, k + 0, 0);
		world.setBlock(i + 6, j + 9, k + 1, 0);
		world.setBlock(i + 6, j + 9, k + 2, 0);
		world.setBlock(i + 6, j + 9, k + 3, 0);
		world.setBlock(i + 6, j + 9, k + 4, 0);
		world.setBlock(i + 6, j + 9, k + 5, 0);
		world.setBlock(i + 6, j + 9, k + 6, 0);
		world.setBlock(i + 6, j + 10, k + 0, 0);
		world.setBlock(i + 6, j + 10, k + 1, 0);
		world.setBlock(i + 6, j + 10, k + 2, 0);
		world.setBlock(i + 6, j + 10, k + 3, 0);
		world.setBlock(i + 6, j + 10, k + 4, 0);
		world.setBlock(i + 6, j + 10, k + 5, 0);
		world.setBlock(i + 6, j + 10, k + 6, 0);
		world.setBlock(i + 6, j + 11, k + 0, 0);
		world.setBlock(i + 6, j + 11, k + 1, 0);
		world.setBlock(i + 6, j + 11, k + 2, 0);
		world.setBlock(i + 6, j + 11, k + 3, 0);
		world.setBlock(i + 6, j + 11, k + 4, 0);
		world.setBlock(i + 6, j + 11, k + 5, 0);
		world.setBlock(i + 6, j + 11, k + 6, 0);
		world.setBlock(i + 6, j + 12, k + 0, 0);
		world.setBlock(i + 6, j + 12, k + 1, 0);
		world.setBlock(i + 6, j + 12, k + 2, 0);
		world.setBlock(i + 6, j + 12, k + 3, 0);
		world.setBlock(i + 6, j + 12, k + 4, 0);
		world.setBlock(i + 6, j + 12, k + 5, 0);
		world.setBlock(i + 6, j + 12, k + 6, 0);
		world.setBlock(i + 3, j + 2, k + 3, NanotechBlock.nuke.blockID);
		return true;
	}
}