/**
 * This work is made available under the terms of the Creative Commons Attribution License:
 * http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en
 * 
 * Cette œuvre est mise à disposition selon les termes de la Licence Creative Commons Attribution:
 * http://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr
 */
package fr.mcnanotech.kevin_68.nanotechmod.main.world;

import java.util.Random;

import net.minecraft.block.Block;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import fr.mcnanotech.kevin_68.nanotechmod.main.blocks.NanotechBlock;

public class WorldModel2 extends WorldGenerator
{
	protected int[] getValidSpawnBlocks()
	{
		return new int[] {Block.stone.blockID, Block.dirt.blockID, NanotechBlock.nanoGrass.blockID, Block.snow.blockID};
	}

	public boolean LocationIsValidSpawn(World world, int x, int y, int z)
	{
		int distanceToAir = 0;
		int checkID = world.getBlockId(x, y, z);

		while(checkID != 0)
		{
			distanceToAir++;
			checkID = world.getBlockId(x, y + distanceToAir, z);
		}

		if(distanceToAir > 3)
		{
			return false;
		}
		y += distanceToAir - 1;

		int blockID = world.getBlockId(x, y, z);
		boolean isAirAbove = world.isAirBlock(x, y + 1, z);
		int blockIDBelow = world.getBlockId(x, y - 1, z);
		for(int valideId : getValidSpawnBlocks())
		{
			if(!isAirAbove)
			{
				return false;
			}
			if(blockID == valideId)
			{
				return true;
			}
			else if(blockID == Block.snow.blockID && blockIDBelow == valideId)
			{
				return true;
			}
		}
		return false;
	}

	public WorldModel2()
	{}

	public boolean generate(World world, Random rand, int x, int y, int z)
	{
		// checz that each corner is one of the valid spawn blocks
		if(!LocationIsValidSpawn(world, x, y, z) || !LocationIsValidSpawn(world, x + 4, y, z) || !LocationIsValidSpawn(world, x + 4, y, z + 9) || !LocationIsValidSpawn(world, x, y, z + 9))
		{
			return false;
		}

		world.setBlockToAir(x + 0, y + 0, z + 0);
		world.setBlockToAir(x + 0, y + 0, z + 1);
		world.setBlockToAir(x + 0, y + 0, z + 2);
		world.setBlockToAir(x + 0, y + 0, z + 3);
		world.setBlock(x + 0, y + 0, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 0, z + 5, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 0, z + 6, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 0, z + 7, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 0, z + 8);
		world.setBlockToAir(x + 0, y + 1, z + 0);
		world.setBlock(x + 0, y + 1, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 1, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 1, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 1, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 1, z + 5, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 1, z + 6, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 1, z + 7, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 1, z + 8);
		world.setBlockToAir(x + 0, y + 2, z + 0);
		world.setBlock(x + 0, y + 2, z + 1, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 2, z + 2);
		world.setBlock(x + 0, y + 2, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 2, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 2, z + 5, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 2, z + 6, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 2, z + 7, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 2, z + 8);
		world.setBlockToAir(x + 0, y + 3, z + 0);
		world.setBlock(x + 0, y + 3, z + 1, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 3, z + 2);
		world.setBlock(x + 0, y + 3, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 3, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 3, z + 5, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 3, z + 6);
		world.setBlock(x + 0, y + 3, z + 7, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 3, z + 8);
		world.setBlockToAir(x + 0, y + 4, z + 0);
		world.setBlock(x + 0, y + 4, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 4, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 4, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 4, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 4, z + 5, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 4, z + 6, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 4, z + 7, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 4, z + 8);
		world.setBlockToAir(x + 0, y + 5, z + 0);
		world.setBlock(x + 0, y + 5, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 5, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 5, z + 3, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 5, z + 4);
		world.setBlockToAir(x + 0, y + 5, z + 5);
		world.setBlockToAir(x + 0, y + 5, z + 6);
		world.setBlockToAir(x + 0, y + 5, z + 7);
		world.setBlockToAir(x + 0, y + 5, z + 8);
		world.setBlockToAir(x + 0, y + 6, z + 0);
		world.setBlockToAir(x + 0, y + 6, z + 1);
		world.setBlockToAir(x + 0, y + 6, z + 2);
		world.setBlock(x + 0, y + 6, z + 3, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 6, z + 4);
		world.setBlockToAir(x + 0, y + 6, z + 5);
		world.setBlockToAir(x + 0, y + 6, z + 6);
		world.setBlockToAir(x + 0, y + 6, z + 7);
		world.setBlockToAir(x + 0, y + 6, z + 8);
		world.setBlockToAir(x + 0, y + 7, z + 0);
		world.setBlockToAir(x + 0, y + 7, z + 1);
		world.setBlockToAir(x + 0, y + 7, z + 2);
		world.setBlock(x + 0, y + 7, z + 3, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 7, z + 4);
		world.setBlockToAir(x + 0, y + 7, z + 5);
		world.setBlockToAir(x + 0, y + 7, z + 6);
		world.setBlockToAir(x + 0, y + 7, z + 7);
		world.setBlockToAir(x + 0, y + 7, z + 8);
		world.setBlockToAir(x + 0, y + 8, z + 0);
		world.setBlockToAir(x + 0, y + 8, z + 1);
		world.setBlock(x + 0, y + 8, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 8, z + 3, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 8, z + 4);
		world.setBlockToAir(x + 0, y + 8, z + 5);
		world.setBlockToAir(x + 0, y + 8, z + 6);
		world.setBlockToAir(x + 0, y + 8, z + 7);
		world.setBlockToAir(x + 0, y + 8, z + 8);
		world.setBlockToAir(x + 0, y + 9, z + 0);
		world.setBlockToAir(x + 0, y + 9, z + 1);
		world.setBlockToAir(x + 0, y + 9, z + 2);
		world.setBlock(x + 0, y + 9, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 0, y + 9, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 9, z + 5);
		world.setBlockToAir(x + 0, y + 9, z + 6);
		world.setBlockToAir(x + 0, y + 9, z + 7);
		world.setBlockToAir(x + 0, y + 9, z + 8);
		world.setBlockToAir(x + 0, y + 10, z + 0);
		world.setBlockToAir(x + 0, y + 10, z + 1);
		world.setBlockToAir(x + 0, y + 10, z + 2);
		world.setBlock(x + 0, y + 10, z + 3, Block.cobblestone.blockID);
		world.setBlockToAir(x + 0, y + 10, z + 4);
		world.setBlockToAir(x + 0, y + 10, z + 5);
		world.setBlockToAir(x + 0, y + 10, z + 6);
		world.setBlockToAir(x + 0, y + 10, z + 7);
		world.setBlockToAir(x + 0, y + 10, z + 8);
		world.setBlockToAir(x + 0, y + 11, z + 0);
		world.setBlockToAir(x + 0, y + 11, z + 1);
		world.setBlockToAir(x + 0, y + 11, z + 2);
		world.setBlockToAir(x + 0, y + 11, z + 3);
		world.setBlockToAir(x + 0, y + 11, z + 4);
		world.setBlockToAir(x + 0, y + 11, z + 5);
		world.setBlockToAir(x + 0, y + 11, z + 6);
		world.setBlockToAir(x + 0, y + 11, z + 7);
		world.setBlockToAir(x + 0, y + 11, z + 8);
		world.setBlockToAir(x + 0, y + 12, z + 1);
		world.setBlockToAir(x + 0, y + 12, z + 2);
		world.setBlockToAir(x + 0, y + 12, z + 3);
		world.setBlockToAir(x + 0, y + 12, z + 4);
		world.setBlockToAir(x + 0, y + 12, z + 5);
		world.setBlockToAir(x + 0, y + 12, z + 6);
		world.setBlockToAir(x + 0, y + 12, z + 7);
		world.setBlockToAir(x + 0, y + 12, z + 8);
		world.setBlock(x + 1, y + 0, z + 0, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 0, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 0, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 0, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 0, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 0, z + 5, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 0, z + 6, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 0, z + 7, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 0, z + 8, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 1, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 1, y + 1, z + 1);
		world.setBlockToAir(x + 1, y + 1, z + 2);
		world.setBlockToAir(x + 1, y + 1, z + 3);
		world.setBlockToAir(x + 1, y + 1, z + 4);
		world.setBlock(x + 1, y + 1, z + 5, Block.stairsCobblestone.blockID, 2, 3);
		world.setBlock(x + 1, y + 1, z + 6, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 1, z + 7, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 1, z + 8, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 2, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 1, y + 2, z + 1);
		world.setBlockToAir(x + 1, y + 2, z + 2);
		world.setBlockToAir(x + 1, y + 2, z + 3);
		world.setBlockToAir(x + 1, y + 2, z + 4);
		world.setBlockToAir(x + 1, y + 2, z + 5);
		world.setBlockToAir(x + 1, y + 2, z + 6);
		world.setBlock(x + 1, y + 2, z + 7, Block.stairsCobblestone.blockID, 1, 3);
		world.setBlock(x + 1, y + 2, z + 8, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 3, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 1, y + 3, z + 1);
		world.setBlockToAir(x + 1, y + 3, z + 2);
		world.setBlockToAir(x + 1, y + 3, z + 3);
		world.setBlockToAir(x + 1, y + 3, z + 4);
		world.setBlockToAir(x + 1, y + 3, z + 5);
		world.setBlockToAir(x + 1, y + 3, z + 6);
		world.setBlockToAir(x + 1, y + 3, z + 7);
		world.setBlockToAir(x + 1, y + 3, z + 8);
		world.setBlock(x + 1, y + 4, z + 0, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 4, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 4, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 4, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 4, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 1, y + 4, z + 5);
		world.setBlockToAir(x + 1, y + 4, z + 6);
		world.setBlockToAir(x + 1, y + 4, z + 7);
		world.setBlockToAir(x + 1, y + 4, z + 8);
		world.setBlockToAir(x + 1, y + 5, z + 0);
		world.setBlockToAir(x + 1, y + 5, z + 1);
		world.setBlockToAir(x + 1, y + 5, z + 2);
		world.setBlockToAir(x + 1, y + 5, z + 3);
		world.setBlock(x + 1, y + 5, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 5, z + 5, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 5, z + 6, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 5, z + 7, Block.cobblestone.blockID);
		world.setBlockToAir(x + 1, y + 5, z + 8);
		world.setBlockToAir(x + 1, y + 6, z + 0);
		world.setBlockToAir(x + 1, y + 6, z + 1);
		world.setBlockToAir(x + 1, y + 6, z + 2);
		world.setBlockToAir(x + 1, y + 6, z + 3);
		world.setBlock(x + 1, y + 6, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 1, y + 6, z + 5);
		world.setBlockToAir(x + 1, y + 6, z + 6);
		world.setBlockToAir(x + 1, y + 6, z + 7);
		world.setBlockToAir(x + 1, y + 6, z + 8);
		world.setBlockToAir(x + 1, y + 7, z + 0);
		world.setBlockToAir(x + 1, y + 7, z + 1);
		world.setBlockToAir(x + 1, y + 7, z + 2);
		world.setBlockToAir(x + 1, y + 7, z + 3);
		world.setBlock(x + 1, y + 7, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 1, y + 7, z + 5);
		world.setBlockToAir(x + 1, y + 7, z + 6);
		world.setBlockToAir(x + 1, y + 7, z + 7);
		world.setBlockToAir(x + 1, y + 7, z + 8);
		world.setBlockToAir(x + 1, y + 8, z + 0);
		world.setBlockToAir(x + 1, y + 8, z + 1);
		world.setBlockToAir(x + 1, y + 8, z + 2);
		world.setBlockToAir(x + 1, y + 8, z + 3);
		world.setBlock(x + 1, y + 8, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 1, y + 8, z + 5);
		world.setBlockToAir(x + 1, y + 8, z + 6);
		world.setBlockToAir(x + 1, y + 8, z + 7);
		world.setBlockToAir(x + 1, y + 8, z + 8);
		world.setBlockToAir(x + 1, y + 9, z + 0);
		world.setBlock(x + 1, y + 9, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 9, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 9, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 1, y + 9, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 1, y + 9, z + 5);
		world.setBlockToAir(x + 1, y + 9, z + 6);
		world.setBlockToAir(x + 1, y + 9, z + 7);
		world.setBlockToAir(x + 1, y + 9, z + 8);
		world.setBlockToAir(x + 1, y + 10, z + 0);
		world.setBlockToAir(x + 1, y + 10, z + 1);
		world.setBlockToAir(x + 1, y + 10, z + 2);
		world.setBlockToAir(x + 1, y + 10, z + 3);
		world.setBlock(x + 1, y + 10, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 1, y + 10, z + 5);
		world.setBlockToAir(x + 1, y + 10, z + 6);
		world.setBlockToAir(x + 1, y + 10, z + 7);
		world.setBlockToAir(x + 1, y + 10, z + 8);
		world.setBlockToAir(x + 1, y + 11, z + 0);
		world.setBlockToAir(x + 1, y + 11, z + 1);
		world.setBlockToAir(x + 1, y + 11, z + 2);
		world.setBlockToAir(x + 1, y + 11, z + 3);
		world.setBlockToAir(x + 1, y + 11, z + 4);
		world.setBlockToAir(x + 1, y + 11, z + 5);
		world.setBlockToAir(x + 1, y + 11, z + 6);
		world.setBlockToAir(x + 1, y + 11, z + 7);
		world.setBlockToAir(x + 1, y + 11, z + 8);
		world.setBlockToAir(x + 1, y + 12, z + 0);
		world.setBlockToAir(x + 1, y + 12, z + 1);
		world.setBlockToAir(x + 1, y + 12, z + 2);
		world.setBlockToAir(x + 1, y + 12, z + 3);
		world.setBlockToAir(x + 1, y + 12, z + 4);
		world.setBlockToAir(x + 1, y + 12, z + 5);
		world.setBlockToAir(x + 1, y + 12, z + 6);
		world.setBlockToAir(x + 1, y + 12, z + 7);
		world.setBlockToAir(x + 1, y + 12, z + 8);
		world.setBlock(x + 2, y + 0, z + 0, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 0, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 0, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 0, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 0, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 0, z + 5, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 0, z + 6, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 0, z + 7, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 0, z + 8);
		world.setBlockToAir(x + 2, y + 1, z + 0);
		world.setBlockToAir(x + 2, y + 1, z + 1);
		world.setBlockToAir(x + 2, y + 1, z + 2);
		world.setBlockToAir(x + 2, y + 1, z + 3);
		world.setBlockToAir(x + 2, y + 1, z + 4);
		world.setBlockToAir(x + 2, y + 1, z + 5);
		world.setBlockToAir(x + 2, y + 1, z + 6);
		world.setBlockToAir(x + 2, y + 1, z + 7);
		world.setBlockToAir(x + 2, y + 1, z + 8);
		world.setBlockToAir(x + 2, y + 2, z + 0);
		world.setBlockToAir(x + 2, y + 2, z + 1);
		world.setBlockToAir(x + 2, y + 2, z + 2);
		world.setBlockToAir(x + 2, y + 2, z + 3);
		world.setBlockToAir(x + 2, y + 2, z + 4);
		world.setBlockToAir(x + 2, y + 2, z + 5);
		world.setBlockToAir(x + 2, y + 2, z + 6);
		world.setBlockToAir(x + 2, y + 2, z + 7);
		world.setBlockToAir(x + 2, y + 2, z + 8);
		world.setBlock(x + 2, y + 3, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 3, z + 1);
		world.setBlockToAir(x + 2, y + 3, z + 2);
		world.setBlockToAir(x + 2, y + 3, z + 3);
		world.setBlockToAir(x + 2, y + 3, z + 4);
		world.setBlockToAir(x + 2, y + 3, z + 5);
		world.setBlockToAir(x + 2, y + 3, z + 6);
		world.setBlockToAir(x + 2, y + 3, z + 7);
		world.setBlockToAir(x + 2, y + 3, z + 8);
		world.setBlock(x + 2, y + 4, z + 0, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 4, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 4, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 4, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 4, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 4, z + 5);
		world.setBlockToAir(x + 2, y + 4, z + 6);
		world.setBlockToAir(x + 2, y + 4, z + 7);
		world.setBlockToAir(x + 2, y + 4, z + 8);
		world.setBlock(x + 2, y + 5, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 5, z + 1);
		world.setBlockToAir(x + 2, y + 5, z + 2);
		world.setBlockToAir(x + 2, y + 5, z + 3);
		world.setBlock(x + 2, y + 5, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 5, z + 5, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 5, z + 6, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 5, z + 7);
		world.setBlockToAir(x + 2, y + 5, z + 8);
		world.setBlockToAir(x + 2, y + 6, z + 0);
		world.setBlockToAir(x + 2, y + 6, z + 1);
		world.setBlockToAir(x + 2, y + 6, z + 2);
		world.setBlockToAir(x + 2, y + 6, z + 3);
		world.setBlockToAir(x + 2, y + 6, z + 4);
		world.setBlockToAir(x + 2, y + 6, z + 5);
		world.setBlockToAir(x + 2, y + 6, z + 6);
		world.setBlockToAir(x + 2, y + 6, z + 7);
		world.setBlockToAir(x + 2, y + 6, z + 8);
		world.setBlockToAir(x + 2, y + 7, z + 0);
		world.setBlockToAir(x + 2, y + 7, z + 1);
		world.setBlockToAir(x + 2, y + 7, z + 2);
		world.setBlockToAir(x + 2, y + 7, z + 3);
		world.setBlockToAir(x + 2, y + 7, z + 4);
		world.setBlockToAir(x + 2, y + 7, z + 5);
		world.setBlockToAir(x + 2, y + 7, z + 6);
		world.setBlockToAir(x + 2, y + 7, z + 7);
		world.setBlockToAir(x + 2, y + 7, z + 8);
		world.setBlock(x + 2, y + 8, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 8, z + 1);
		world.setBlockToAir(x + 2, y + 8, z + 2);
		world.setBlockToAir(x + 2, y + 8, z + 3);
		world.setBlock(x + 2, y + 8, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 8, z + 5);
		world.setBlockToAir(x + 2, y + 8, z + 6);
		world.setBlockToAir(x + 2, y + 8, z + 7);
		world.setBlockToAir(x + 2, y + 8, z + 8);
		world.setBlock(x + 2, y + 9, z + 0, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 9, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 9, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 9, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 2, y + 9, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 9, z + 5);
		world.setBlockToAir(x + 2, y + 9, z + 6);
		world.setBlockToAir(x + 2, y + 9, z + 7);
		world.setBlockToAir(x + 2, y + 9, z + 8);
		world.setBlock(x + 2, y + 10, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 10, z + 1);
		world.setBlockToAir(x + 2, y + 10, z + 2);
		world.setBlockToAir(x + 2, y + 10, z + 3);
		world.setBlock(x + 2, y + 10, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 10, z + 5);
		world.setBlockToAir(x + 2, y + 10, z + 6);
		world.setBlockToAir(x + 2, y + 10, z + 7);
		world.setBlockToAir(x + 2, y + 10, z + 8);
		world.setBlock(x + 2, y + 11, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 11, z + 1);
		world.setBlockToAir(x + 2, y + 11, z + 2);
		world.setBlockToAir(x + 2, y + 11, z + 3);
		world.setBlock(x + 2, y + 11, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 2, y + 11, z + 5);
		world.setBlockToAir(x + 2, y + 11, z + 6);
		world.setBlockToAir(x + 2, y + 11, z + 7);
		world.setBlockToAir(x + 2, y + 11, z + 8);
		world.setBlockToAir(x + 2, y + 12, z + 0);
		world.setBlockToAir(x + 2, y + 12, z + 1);
		world.setBlockToAir(x + 2, y + 12, z + 2);
		world.setBlockToAir(x + 2, y + 12, z + 3);
		world.setBlockToAir(x + 2, y + 12, z + 4);
		world.setBlockToAir(x + 2, y + 12, z + 5);
		world.setBlockToAir(x + 2, y + 12, z + 6);
		world.setBlockToAir(x + 2, y + 12, z + 7);
		world.setBlockToAir(x + 2, y + 12, z + 8);
		world.setBlock(x + 3, y + 0, z + 0, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 0, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 0, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 0, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 0, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 0, z + 5, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 0, z + 6, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 0, z + 7);
		world.setBlockToAir(x + 3, y + 0, z + 8);
		world.setBlock(x + 3, y + 1, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 1, z + 1);
		world.setBlockToAir(x + 3, y + 1, z + 2);
		world.setBlockToAir(x + 3, y + 1, z + 4);
		world.setBlockToAir(x + 3, y + 1, z + 5);
		world.setBlockToAir(x + 3, y + 1, z + 6);
		world.setBlockToAir(x + 3, y + 1, z + 7);
		world.setBlockToAir(x + 3, y + 1, z + 8);
		world.setBlock(x + 3, y + 2, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 2, z + 1);
		world.setBlockToAir(x + 3, y + 2, z + 2);
		world.setBlockToAir(x + 3, y + 2, z + 4);
		world.setBlockToAir(x + 3, y + 2, z + 5);
		world.setBlockToAir(x + 3, y + 2, z + 6);
		world.setBlockToAir(x + 3, y + 2, z + 7);
		world.setBlockToAir(x + 3, y + 2, z + 8);
		world.setBlock(x + 3, y + 3, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 3, z + 1);
		world.setBlockToAir(x + 3, y + 3, z + 2);
		world.setBlockToAir(x + 3, y + 3, z + 4);
		world.setBlockToAir(x + 3, y + 3, z + 5);
		world.setBlockToAir(x + 3, y + 3, z + 6);
		world.setBlockToAir(x + 3, y + 3, z + 7);
		world.setBlockToAir(x + 3, y + 3, z + 8);
		world.setBlock(x + 3, y + 4, z + 0, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 4, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 4, z + 2, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 4, z + 3);
		world.setBlock(x + 3, y + 4, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 4, z + 5);
		world.setBlockToAir(x + 3, y + 4, z + 6);
		world.setBlockToAir(x + 3, y + 4, z + 7);
		world.setBlockToAir(x + 3, y + 4, z + 8);
		world.setBlock(x + 3, y + 5, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 5, z + 1);
		world.setBlockToAir(x + 3, y + 5, z + 2);
		world.setBlockToAir(x + 3, y + 5, z + 3);
		world.setBlock(x + 3, y + 5, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 5, z + 5, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 5, z + 6);
		world.setBlockToAir(x + 3, y + 5, z + 7);
		world.setBlockToAir(x + 3, y + 5, z + 8);
		world.setBlock(x + 3, y + 6, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 6, z + 1);
		world.setBlockToAir(x + 3, y + 6, z + 2);
		world.setBlockToAir(x + 3, y + 6, z + 3);
		world.setBlock(x + 3, y + 6, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 6, z + 5);
		world.setBlockToAir(x + 3, y + 6, z + 6);
		world.setBlockToAir(x + 3, y + 6, z + 7);
		world.setBlockToAir(x + 3, y + 6, z + 8);
		world.setBlock(x + 3, y + 7, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 7, z + 1);
		world.setBlockToAir(x + 3, y + 7, z + 2);
		world.setBlock(x + 3, y + 7, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 7, z + 5);
		world.setBlockToAir(x + 3, y + 7, z + 6);
		world.setBlockToAir(x + 3, y + 7, z + 7);
		world.setBlockToAir(x + 3, y + 7, z + 8);
		world.setBlock(x + 3, y + 8, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 8, z + 1);
		world.setBlockToAir(x + 3, y + 8, z + 2);
		world.setBlock(x + 3, y + 8, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 8, z + 5);
		world.setBlockToAir(x + 3, y + 8, z + 6);
		world.setBlockToAir(x + 3, y + 8, z + 7);
		world.setBlockToAir(x + 3, y + 8, z + 8);
		world.setBlock(x + 3, y + 9, z + 0, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 9, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 9, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 3, y + 9, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 9, z + 5);
		world.setBlockToAir(x + 3, y + 9, z + 6);
		world.setBlockToAir(x + 3, y + 9, z + 7);
		world.setBlockToAir(x + 3, y + 9, z + 8);
		world.setBlock(x + 3, y + 10, z + 0, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 10, z + 1);
		world.setBlockToAir(x + 3, y + 10, z + 2);
		world.setBlockToAir(x + 3, y + 10, z + 3);
		world.setBlock(x + 3, y + 10, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 3, y + 10, z + 5);
		world.setBlockToAir(x + 3, y + 10, z + 6);
		world.setBlockToAir(x + 3, y + 10, z + 7);
		world.setBlockToAir(x + 3, y + 10, z + 8);
		world.setBlockToAir(x + 3, y + 11, z + 0);
		world.setBlockToAir(x + 3, y + 11, z + 1);
		world.setBlockToAir(x + 3, y + 11, z + 2);
		world.setBlockToAir(x + 3, y + 11, z + 3);
		world.setBlockToAir(x + 3, y + 11, z + 4);
		world.setBlockToAir(x + 3, y + 11, z + 5);
		world.setBlockToAir(x + 3, y + 11, z + 6);
		world.setBlockToAir(x + 3, y + 11, z + 7);
		world.setBlockToAir(x + 3, y + 11, z + 8);
		world.setBlockToAir(x + 3, y + 12, z + 0);
		world.setBlockToAir(x + 3, y + 12, z + 1);
		world.setBlockToAir(x + 3, y + 12, z + 2);
		world.setBlockToAir(x + 3, y + 12, z + 3);
		world.setBlockToAir(x + 3, y + 12, z + 4);
		world.setBlockToAir(x + 3, y + 12, z + 5);
		world.setBlockToAir(x + 3, y + 12, z + 6);
		world.setBlockToAir(x + 3, y + 12, z + 7);
		world.setBlockToAir(x + 3, y + 12, z + 8);
		world.setBlockToAir(x + 4, y + 0, z + 0);
		world.setBlockToAir(x + 4, y + 0, z + 1);
		world.setBlockToAir(x + 4, y + 0, z + 2);
		world.setBlockToAir(x + 4, y + 0, z + 3);
		world.setBlock(x + 4, y + 0, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 0, z + 5, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 0, z + 6);
		world.setBlockToAir(x + 4, y + 0, z + 7);
		world.setBlockToAir(x + 4, y + 1, z + 0);
		world.setBlock(x + 4, y + 1, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 1, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 1, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 1, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 1, z + 5, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 1, z + 6);
		world.setBlockToAir(x + 4, y + 1, z + 7);
		world.setBlockToAir(x + 4, y + 1, z + 8);
		world.setBlockToAir(x + 4, y + 2, z + 0);
		world.setBlock(x + 4, y + 2, z + 1, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 2, z + 2);
		world.setBlock(x + 4, y + 2, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 2, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 2, z + 5);
		world.setBlockToAir(x + 4, y + 2, z + 6);
		world.setBlockToAir(x + 4, y + 2, z + 7);
		world.setBlockToAir(x + 4, y + 2, z + 8);
		world.setBlockToAir(x + 4, y + 3, z + 0);
		world.setBlock(x + 4, y + 3, z + 1, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 3, z + 2);
		world.setBlock(x + 4, y + 3, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 3, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 3, z + 5);
		world.setBlockToAir(x + 4, y + 3, z + 6);
		world.setBlockToAir(x + 4, y + 3, z + 7);
		world.setBlockToAir(x + 4, y + 3, z + 8);
		world.setBlock(x + 4, y + 4, z + 0, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 4, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 4, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 4, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 4, z + 4, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 4, z + 5, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 4, z + 6);
		world.setBlockToAir(x + 4, y + 4, z + 7);
		world.setBlockToAir(x + 4, y + 4, z + 8);
		world.setBlockToAir(x + 4, y + 5, z + 0);
		world.setBlock(x + 4, y + 5, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 5, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 5, z + 3, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 5, z + 4);
		world.setBlockToAir(x + 4, y + 5, z + 5);
		world.setBlockToAir(x + 4, y + 5, z + 6);
		world.setBlockToAir(x + 4, y + 5, z + 7);
		world.setBlockToAir(x + 4, y + 5, z + 8);
		world.setBlockToAir(x + 4, y + 6, z + 0);
		world.setBlock(x + 4, y + 6, z + 1, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 6, z + 2);
		world.setBlock(x + 4, y + 6, z + 3, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 6, z + 4);
		world.setBlockToAir(x + 4, y + 6, z + 5);
		world.setBlockToAir(x + 4, y + 6, z + 6);
		world.setBlockToAir(x + 4, y + 6, z + 7);
		world.setBlockToAir(x + 4, y + 6, z + 8);
		world.setBlockToAir(x + 4, y + 7, z + 0);
		world.setBlock(x + 4, y + 7, z + 1, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 7, z + 2);
		world.setBlock(x + 4, y + 7, z + 3, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 7, z + 4);
		world.setBlockToAir(x + 4, y + 7, z + 5);
		world.setBlockToAir(x + 4, y + 7, z + 6);
		world.setBlockToAir(x + 4, y + 7, z + 7);
		world.setBlockToAir(x + 4, y + 7, z + 8);
		world.setBlockToAir(x + 4, y + 8, z + 0);
		world.setBlock(x + 4, y + 8, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 8, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 8, z + 3, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 8, z + 4);
		world.setBlockToAir(x + 4, y + 8, z + 5);
		world.setBlockToAir(x + 4, y + 8, z + 6);
		world.setBlockToAir(x + 4, y + 8, z + 7);
		world.setBlockToAir(x + 4, y + 8, z + 8);
		world.setBlock(x + 4, y + 9, z + 0, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 9, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 9, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 9, z + 3, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 9, z + 4, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 9, z + 5);
		world.setBlockToAir(x + 4, y + 9, z + 6);
		world.setBlockToAir(x + 4, y + 9, z + 7);
		world.setBlockToAir(x + 4, y + 9, z + 8);
		world.setBlockToAir(x + 4, y + 10, z + 0);
		world.setBlock(x + 4, y + 10, z + 1, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 10, z + 2, Block.cobblestone.blockID);
		world.setBlock(x + 4, y + 10, z + 3, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 10, z + 4);
		world.setBlockToAir(x + 4, y + 10, z + 5);
		world.setBlockToAir(x + 4, y + 10, z + 6);
		world.setBlockToAir(x + 4, y + 10, z + 7);
		world.setBlockToAir(x + 4, y + 10, z + 8);
		world.setBlockToAir(x + 4, y + 11, z + 0);
		world.setBlockToAir(x + 4, y + 11, z + 1);
		world.setBlock(x + 4, y + 11, z + 2, Block.cobblestone.blockID);
		world.setBlockToAir(x + 4, y + 11, z + 3);
		world.setBlockToAir(x + 4, y + 11, z + 4);
		world.setBlockToAir(x + 4, y + 11, z + 5);
		world.setBlockToAir(x + 4, y + 11, z + 6);
		world.setBlockToAir(x + 4, y + 11, z + 7);
		world.setBlockToAir(x + 4, y + 11, z + 8);
		world.setBlockToAir(x + 4, y + 12, z + 0);
		world.setBlockToAir(x + 4, y + 12, z + 1);
		world.setBlockToAir(x + 4, y + 12, z + 2);
		world.setBlockToAir(x + 4, y + 12, z + 3);
		world.setBlockToAir(x + 4, y + 12, z + 4);
		world.setBlockToAir(x + 4, y + 12, z + 5);
		world.setBlockToAir(x + 4, y + 12, z + 6);
		world.setBlockToAir(x + 4, y + 12, z + 7);
		world.setBlockToAir(x + 4, y + 12, z + 8);
		world.setBlock(x + 3, y + 1, z + 3, Block.ladder.blockID, 4, 3);
		world.setBlock(x + 3, y + 2, z + 3, Block.ladder.blockID, 4, 3);
		world.setBlock(x + 3, y + 3, z + 3, Block.ladder.blockID, 4, 3);
		world.setBlock(x + 3, y + 7, z + 3, Block.ladder.blockID, 4, 3);
		world.setBlock(x + 3, y + 8, z + 3, Block.ladder.blockID, 4, 3);
		world.setBlock(x + 3, y + 9, z + 3, Block.ladder.blockID, 4, 3);

		return true;
	}
}