package fr.mcnanotech.kevin_68.nanotechmod.main.world;

import java.util.Random;

import net.minecraft.block.Block;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import fr.mcnanotech.kevin_68.nanotechmod.main.blocks.NanotechBlock;

public class WorldModel5 extends WorldGenerator
{
	protected int[] GetValidSpawnBlocks()
	{
		return new int[] {Block.stone.blockID, Block.dirt.blockID, NanotechBlock.nanoGrass.blockID, Block.snow.blockID};
	}

	public boolean LocationIsValidSpawn(World world, int x, int y, int z)
	{
		int distanceToAir = 0;
		int checkID = world.getBlockId(x, y, z);

		while(checkID != 0)
		{
			distanceToAir++;
			checkID = world.getBlockId(x, y + distanceToAir, z);
		}

		if(distanceToAir > 3)
		{
			return false;
		}
		y += distanceToAir - 1;

		int blockID = world.getBlockId(x, y, z);
		boolean isAirAbove = world.isAirBlock(x, y + 1, z);
		int blockIDBelow = world.getBlockId(x, y - 1, z);
		for(int valideSpawn : GetValidSpawnBlocks())
		{
			if(!isAirAbove)
			{
				return false;
			}
			if(blockID == valideSpawn)
			{
				return true;
			}
			else if(blockID == Block.snow.blockID && blockIDBelow == valideSpawn)
			{
				return true;
			}
		}
		return false;
	}

	public WorldModel5()
	{}

	public boolean generate(World world, Random rand, int x, int y, int z)
	{
		if(!LocationIsValidSpawn(world, x, y, z) || !LocationIsValidSpawn(world, x + 6, y, z) || !LocationIsValidSpawn(world, x + 6, y, z + 6) || !LocationIsValidSpawn(world, x, y, z + 6))
		{
			return false;
		}

		world.setBlock(x, y - 4, z, Block.stone.blockID);
		world.setBlock(x, y - 4, z + 1, Block.stone.blockID);
		world.setBlock(x, y - 4, z + 2, Block.stone.blockID);
		world.setBlock(x, y - 4, z + 3, Block.stone.blockID);
		world.setBlock(x, y - 4, z + 4, Block.stone.blockID);
		world.setBlock(x, y - 4, z + 5, Block.stone.blockID);
		world.setBlock(x, y - 4, z + 6, Block.stone.blockID);
		world.setBlock(x, y - 3, z, Block.stone.blockID);
		world.setBlock(x, y - 3, z + 1, Block.stone.blockID);
		world.setBlock(x, y - 3, z + 2, Block.stone.blockID);
		world.setBlock(x, y - 3, z + 3, Block.stone.blockID);
		world.setBlock(x, y - 3, z + 4, Block.stone.blockID);
		world.setBlock(x, y - 3, z + 5, Block.stone.blockID);
		world.setBlock(x, y - 3, z + 6, Block.stone.blockID);
		world.setBlock(x, y - 2, z, Block.dirt.blockID);
		world.setBlock(x, y - 2, z + 1, Block.dirt.blockID);
		world.setBlock(x, y - 2, z + 2, Block.dirt.blockID);
		world.setBlock(x, y - 2, z + 3, Block.dirt.blockID);
		world.setBlock(x, y - 2, z + 4, Block.dirt.blockID);
		world.setBlock(x, y - 2, z + 5, Block.dirt.blockID);
		world.setBlock(x, y - 2, z + 6, Block.dirt.blockID);
		world.setBlock(x, y - 1, z, Block.dirt.blockID);
		world.setBlock(x, y - 1, z + 1, Block.dirt.blockID);
		world.setBlock(x, y - 1, z + 2, Block.dirt.blockID);
		world.setBlock(x, y - 1, z + 3, Block.dirt.blockID);
		world.setBlock(x, y - 1, z + 4, Block.dirt.blockID);
		world.setBlock(x, y - 1, z + 5, Block.dirt.blockID);
		world.setBlock(x, y - 1, z + 6, Block.dirt.blockID);
		world.setBlock(x, y, z, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x, y, z + 1, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x, y, z + 2, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x, y, z + 3, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x, y, z + 4, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x, y, z + 5, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x, y, z + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x, y + 1, z, 0);
		world.setBlock(x, y + 1, z + 1, 0);
		world.setBlock(x, y + 1, z + 2, 0);
		world.setBlock(x, y + 1, z + 3, 0);
		world.setBlock(x, y + 1, z + 4, 0);
		world.setBlock(x, y + 1, z + 5, 0);
		world.setBlock(x, y + 1, z + 6, 0);
		world.setBlock(x, y + 2, z, 0);
		world.setBlock(x, y + 2, z + 1, 0);
		world.setBlock(x, y + 2, z + 2, 0);
		world.setBlock(x, y + 2, z + 3, 0);
		world.setBlock(x, y + 2, z + 4, 0);
		world.setBlock(x, y + 2, z + 5, 0);
		world.setBlock(x, y + 2, z + 6, 0);
		world.setBlock(x, y + 3, z, 0);
		world.setBlock(x, y + 3, z + 1, 0);
		world.setBlock(x, y + 3, z + 2, 0);
		world.setBlock(x, y + 3, z + 3, 0);
		world.setBlock(x, y + 3, z + 4, 0);
		world.setBlock(x, y + 3, z + 5, 0);
		world.setBlock(x, y + 3, z + 6, 0);
		world.setBlock(x, y + 4, z, 0);
		world.setBlock(x, y + 4, z + 1, 0);
		world.setBlock(x, y + 4, z + 2, 0);
		world.setBlock(x, y + 4, z + 3, 0);
		world.setBlock(x, y + 4, z + 4, 0);
		world.setBlock(x, y + 4, z + 5, 0);
		world.setBlock(x, y + 4, z + 6, 0);
		world.setBlock(x, y + 5, z, 0);
		world.setBlock(x, y + 5, z + 1, 0);
		world.setBlock(x, y + 5, z + 2, 0);
		world.setBlock(x, y + 5, z + 3, 0);
		world.setBlock(x, y + 5, z + 4, 0);
		world.setBlock(x, y + 5, z + 5, 0);
		world.setBlock(x, y + 5, z + 6, 0);
		world.setBlock(x, y + 6, z, 0);
		world.setBlock(x, y + 6, z + 1, 0);
		world.setBlock(x, y + 6, z + 2, 0);
		world.setBlock(x, y + 6, z + 3, 0);
		world.setBlock(x, y + 6, z + 4, 0);
		world.setBlock(x, y + 6, z + 5, 0);
		world.setBlock(x, y + 6, z + 6, 0);
		world.setBlock(x, y + 7, z, 0);
		world.setBlock(x, y + 7, z + 1, 0);
		world.setBlock(x, y + 7, z + 2, 0);
		world.setBlock(x, y + 7, z + 3, 0);
		world.setBlock(x, y + 7, z + 4, 0);
		world.setBlock(x, y + 7, z + 5, 0);
		world.setBlock(x, y + 7, z + 6, 0);
		world.setBlock(x, y + 8, z, 0);
		world.setBlock(x, y + 8, z + 1, 0);
		world.setBlock(x, y + 8, z + 2, 0);
		world.setBlock(x, y + 8, z + 3, 0);
		world.setBlock(x, y + 8, z + 4, 0);
		world.setBlock(x, y + 8, z + 5, 0);
		world.setBlock(x, y + 8, z + 6, 0);
		world.setBlock(x + 1, y - 4, z, Block.stone.blockID);
		world.setBlock(x + 1, y - 4, z + 1, Block.stone.blockID);
		world.setBlock(x + 1, y - 4, z + 2, Block.stone.blockID);
		world.setBlock(x + 1, y - 4, z + 3, Block.stone.blockID);
		world.setBlock(x + 1, y - 4, z + 4, Block.stone.blockID);
		world.setBlock(x + 1, y - 4, z + 5, Block.stone.blockID);
		world.setBlock(x + 1, y - 4, z + 6, Block.stone.blockID);
		world.setBlock(x + 1, y - 3, z, Block.stone.blockID);
		world.setBlock(x + 1, y - 3, z + 1, Block.stone.blockID);
		world.setBlock(x + 1, y - 3, z + 2, Block.stone.blockID);
		world.setBlock(x + 1, y - 3, z + 3, Block.stone.blockID);
		world.setBlock(x + 1, y - 3, z + 4, Block.stone.blockID);
		world.setBlock(x + 1, y - 3, z + 5, Block.stone.blockID);
		world.setBlock(x + 1, y - 3, z + 6, Block.stone.blockID);
		world.setBlock(x + 1, y - 2, z, Block.dirt.blockID);
		world.setBlock(x + 1, y - 2, z + 1, Block.dirt.blockID);
		world.setBlock(x + 1, y - 2, z + 2, Block.dirt.blockID);
		world.setBlock(x + 1, y - 2, z + 3, Block.dirt.blockID);
		world.setBlock(x + 1, y - 2, z + 4, Block.dirt.blockID);
		world.setBlock(x + 1, y - 2, z + 5, Block.dirt.blockID);
		world.setBlock(x + 1, y - 2, z + 6, Block.dirt.blockID);
		world.setBlock(x + 1, y - 1, z, Block.dirt.blockID);
		world.setBlock(x + 1, y - 1, z + 1, Block.dirt.blockID);
		world.setBlock(x + 1, y - 1, z + 2, NanotechBlock.nukeBuildingStairs.blockID, 4, 0);
		world.setBlock(x + 1, y - 1, z + 3, NanotechBlock.nukeBuildingStairs.blockID, 4, 0);
		world.setBlock(x + 1, y - 1, z + 4, NanotechBlock.nukeBuildingStairs.blockID, 4, 0);
		world.setBlock(x + 1, y - 1, z + 5, Block.dirt.blockID);
		world.setBlock(x + 1, y - 1, z + 6, Block.dirt.blockID);
		world.setBlock(x + 1, y, z, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 1, y, z + 1, NanotechBlock.nukeBuildingBlock.blockID, 8, 0);
		world.setBlock(x + 1, y, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y, z + 5, NanotechBlock.nukeBuildingBlock.blockID, 7, 0);
		world.setBlock(x + 1, y, z + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 1, y + 1, z, 0);
		world.setBlock(x + 1, y + 1, z + 1, NanotechBlock.nukeBuildingBlock.blockID, 8, 0);
		world.setBlock(x + 1, y + 1, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y + 1, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y + 1, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y + 1, z + 5, NanotechBlock.nukeBuildingBlock.blockID, 7, 0);
		world.setBlock(x + 1, y + 1, z + 6, 0);
		world.setBlock(x + 1, y + 2, z, 0);
		world.setBlock(x + 1, y + 2, z + 1, NanotechBlock.nukeBuildingBlock.blockID, 8, 0);
		world.setBlock(x + 1, y + 2, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y + 2, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y + 2, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y + 2, z + 5, NanotechBlock.nukeBuildingBlock.blockID, 7, 0);
		world.setBlock(x + 1, y + 2, z + 6, 0);
		world.setBlock(x + 1, y + 3, z, 0);
		world.setBlock(x + 1, y + 3, z + 1, 0);
		world.setBlock(x + 1, y + 3, z + 2, NanotechBlock.nukeBuildingStairs.blockID);
		world.setBlock(x + 1, y + 3, z + 3, NanotechBlock.nukeBuildingStairs.blockID);
		world.setBlock(x + 1, y + 3, z + 4, NanotechBlock.nukeBuildingStairs.blockID);
		world.setBlock(x + 1, y + 3, z + 5, 0);
		world.setBlock(x + 1, y + 3, z + 6, 0);
		world.setBlock(x + 1, y + 4, z, 0);
		world.setBlock(x + 1, y + 4, z + 1, 0);
		world.setBlock(x + 1, y + 4, z + 2, 0);
		world.setBlock(x + 1, y + 4, z + 3, NanotechBlock.nukeBuildingBlock.blockID, 3, 0);
		world.setBlock(x + 1, y + 4, z + 4, 0);
		world.setBlock(x + 1, y + 4, z + 5, 0);
		world.setBlock(x + 1, y + 4, z + 6, 0);
		world.setBlock(x + 1, y + 5, z, 0);
		world.setBlock(x + 1, y + 5, z + 1, 0);
		world.setBlock(x + 1, y + 5, z + 2, 0);
		world.setBlock(x + 1, y + 5, z + 3, 0);
		world.setBlock(x + 1, y + 5, z + 4, 0);
		world.setBlock(x + 1, y + 5, z + 5, 0);
		world.setBlock(x + 1, y + 5, z + 6, 0);
		world.setBlock(x + 1, y + 6, z, 0);
		world.setBlock(x + 1, y + 6, z + 1, 0);
		world.setBlock(x + 1, y + 6, z + 2, 0);
		world.setBlock(x + 1, y + 6, z + 3, 0);
		world.setBlock(x + 1, y + 6, z + 4, 0);
		world.setBlock(x + 1, y + 6, z + 5, 0);
		world.setBlock(x + 1, y + 6, z + 6, 0);
		world.setBlock(x + 1, y + 7, z, 0);
		world.setBlock(x + 1, y + 7, z + 1, 0);
		world.setBlock(x + 1, y + 7, z + 2, 0);
		world.setBlock(x + 1, y + 7, z + 3, 0);
		world.setBlock(x + 1, y + 7, z + 4, 0);
		world.setBlock(x + 1, y + 7, z + 5, 0);
		world.setBlock(x + 1, y + 7, z + 6, 0);
		world.setBlock(x + 1, y + 8, z, 0);
		world.setBlock(x + 1, y + 8, z + 1, NanotechBlock.nukeBuildingBlock.blockID, 8, 0);
		world.setBlock(x + 1, y + 8, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y + 8, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y + 8, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 1, y + 8, z + 5, NanotechBlock.nukeBuildingBlock.blockID, 7, 0);
		world.setBlock(x + 1, y + 8, z + 6, 0);
		world.setBlock(x + 2, y - 4, z, Block.stone.blockID);
		world.setBlock(x + 2, y - 4, z + 1, Block.stone.blockID);
		world.setBlock(x + 2, y - 4, z + 2, Block.stone.blockID);
		world.setBlock(x + 2, y - 4, z + 3, Block.stone.blockID);
		world.setBlock(x + 2, y - 4, z + 4, Block.stone.blockID);
		world.setBlock(x + 2, y - 4, z + 5, Block.stone.blockID);
		world.setBlock(x + 2, y - 4, z + 6, Block.stone.blockID);
		world.setBlock(x + 2, y - 3, z, Block.stone.blockID);
		world.setBlock(x + 2, y - 3, z + 1, Block.stone.blockID);
		world.setBlock(x + 2, y - 3, z + 2, Block.stone.blockID);
		world.setBlock(x + 2, y - 3, z + 3, NanotechBlock.nukeBuildingStairs.blockID, 4, 0);
		world.setBlock(x + 2, y - 3, z + 4, Block.stone.blockID);
		world.setBlock(x + 2, y - 3, z + 5, Block.stone.blockID);
		world.setBlock(x + 2, y - 3, z + 6, Block.stone.blockID);
		world.setBlock(x + 2, y - 2, z, Block.dirt.blockID);
		world.setBlock(x + 2, y - 2, z + 1, Block.dirt.blockID);
		world.setBlock(x + 2, y - 2, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y - 2, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y - 2, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y - 2, z + 5, Block.dirt.blockID);
		world.setBlock(x + 2, y - 2, z + 6, Block.dirt.blockID);
		world.setBlock(x + 2, y - 1, z, Block.dirt.blockID);
		world.setBlock(x + 2, y - 1, z + 1, NanotechBlock.nukeBuildingStairs.blockID, 6, 0);
		world.setBlock(x + 2, y - 1, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y - 1, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y - 1, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y - 1, z + 5, NanotechBlock.nukeBuildingStairs.blockID, 7, 0);
		world.setBlock(x + 2, y - 1, z + 6, Block.dirt.blockID);
		world.setBlock(x + 2, y, z, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 2, y, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y, z + 2, Block.tnt.blockID);
		world.setBlock(x + 2, y, z + 3, Block.tnt.blockID);
		world.setBlock(x + 2, y, z + 4, Block.tnt.blockID);
		world.setBlock(x + 2, y, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y, z + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 2, y + 1, z, 0);
		world.setBlock(x + 2, y + 1, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y + 1, z + 2, Block.tnt.blockID);
		world.setBlock(x + 2, y + 1, z + 3, Block.tnt.blockID);
		world.setBlock(x + 2, y + 1, z + 4, Block.tnt.blockID);
		world.setBlock(x + 2, y + 1, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y + 1, z + 6, 0);
		world.setBlock(x + 2, y + 2, z, 0);
		world.setBlock(x + 2, y + 2, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y + 2, z + 2, Block.tnt.blockID);
		world.setBlock(x + 2, y + 2, z + 3, Block.tnt.blockID);
		world.setBlock(x + 2, y + 2, z + 4, Block.tnt.blockID);
		world.setBlock(x + 2, y + 2, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y + 2, z + 6, 0);
		world.setBlock(x + 2, y + 3, z, 0);
		world.setBlock(x + 2, y + 3, z + 1, NanotechBlock.nukeBuildingStairs.blockID, 2, 0);
		world.setBlock(x + 2, y + 3, z + 2, Block.tnt.blockID);
		world.setBlock(x + 2, y + 3, z + 3, Block.tnt.blockID);
		world.setBlock(x + 2, y + 3, z + 4, Block.tnt.blockID);
		world.setBlock(x + 2, y + 3, z + 5, NanotechBlock.nukeBuildingStairs.blockID, 3, 0);
		world.setBlock(x + 2, y + 3, z + 6, 0);
		world.setBlock(x + 2, y + 4, z, 0);
		world.setBlock(x + 2, y + 4, z + 1, 0);
		world.setBlock(x + 2, y + 4, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y + 4, z + 3, Block.tnt.blockID);
		world.setBlock(x + 2, y + 4, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y + 4, z + 5, 0);
		world.setBlock(x + 2, y + 4, z + 6, 0);
		world.setBlock(x + 2, y + 5, z, 0);
		world.setBlock(x + 2, y + 5, z + 1, 0);
		world.setBlock(x + 2, y + 5, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y + 5, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y + 5, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y + 5, z + 5, 0);
		world.setBlock(x + 2, y + 5, z + 6, 0);
		world.setBlock(x + 2, y + 6, z, 0);
		world.setBlock(x + 2, y + 6, z + 1, 0);
		world.setBlock(x + 2, y + 6, z + 2, 0);
		world.setBlock(x + 2, y + 6, z + 3, NanotechBlock.nukeBuildingStairs.blockID);
		world.setBlock(x + 2, y + 6, z + 4, 0);
		world.setBlock(x + 2, y + 6, z + 5, 0);
		world.setBlock(x + 2, y + 6, z + 6, 0);
		world.setBlock(x + 2, y + 7, z, 0);
		world.setBlock(x + 2, y + 7, z + 1, 0);
		world.setBlock(x + 2, y + 7, z + 2, 0);
		world.setBlock(x + 2, y + 7, z + 3, 0);
		world.setBlock(x + 2, y + 7, z + 4, 0);
		world.setBlock(x + 2, y + 7, z + 5, 0);
		world.setBlock(x + 2, y + 7, z + 6, 0);
		world.setBlock(x + 2, y + 8, z, 0);
		world.setBlock(x + 2, y + 8, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y + 8, z + 2, NanotechBlock.nukeBuildingBlock.blockID, 5, 0);
		world.setBlock(x + 2, y + 8, z + 3, NanotechBlock.nukeBuildingStairs.blockID, 1, 0);
		world.setBlock(x + 2, y + 8, z + 4, NanotechBlock.nukeBuildingBlock.blockID, 6, 0);
		world.setBlock(x + 2, y + 8, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 2, y + 8, z + 6, 0);
		world.setBlock(x + 3, y - 4, z, Block.stone.blockID);
		world.setBlock(x + 3, y - 4, z + 1, Block.stone.blockID);
		world.setBlock(x + 3, y - 4, z + 2, Block.stone.blockID);
		world.setBlock(x + 3, y - 4, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y - 4, z + 4, Block.stone.blockID);
		world.setBlock(x + 3, y - 4, z + 5, Block.stone.blockID);
		world.setBlock(x + 3, y - 4, z + 6, Block.stone.blockID);
		world.setBlock(x + 3, y - 3, z, Block.stone.blockID);
		world.setBlock(x + 3, y - 3, z + 1, Block.stone.blockID);
		world.setBlock(x + 3, y - 3, z + 2, NanotechBlock.nukeBuildingStairs.blockID, 6, 0);
		world.setBlock(x + 3, y - 3, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y - 3, z + 4, NanotechBlock.nukeBuildingStairs.blockID, 7, 0);
		world.setBlock(x + 3, y - 3, z + 5, Block.stone.blockID);
		world.setBlock(x + 3, y - 3, z + 6, Block.stone.blockID);
		world.setBlock(x + 3, y - 2, z, Block.dirt.blockID);
		world.setBlock(x + 3, y - 2, z + 1, Block.dirt.blockID);
		world.setBlock(x + 3, y - 2, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y - 2, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y - 2, z + 5, Block.dirt.blockID);
		world.setBlock(x + 3, y - 2, z + 6, Block.dirt.blockID);
		world.setBlock(x + 3, y - 1, z, Block.dirt.blockID);
		world.setBlock(x + 3, y - 1, z + 1, NanotechBlock.nukeBuildingStairs.blockID, 6, 0);
		world.setBlock(x + 3, y - 1, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y - 1, z + 3, Block.oreDiamond.blockID);
		world.setBlock(x + 3, y - 1, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y - 1, z + 5, NanotechBlock.nukeBuildingStairs.blockID, 7, 0);
		world.setBlock(x + 3, y - 1, z + 6, Block.dirt.blockID);
		world.setBlock(x + 3, y, z, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 3, y, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y, z + 2, Block.tnt.blockID);
		world.setBlock(x + 3, y, z + 3, Block.tnt.blockID);
		world.setBlock(x + 3, y, z + 4, Block.tnt.blockID);
		world.setBlock(x + 3, y, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y, z + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 3, y + 1, z, 0);
		world.setBlock(x + 3, y + 1, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y + 1, z + 2, Block.tnt.blockID);
		world.setBlock(x + 3, y + 1, z + 3, Block.tnt.blockID);
		world.setBlock(x + 3, y + 1, z + 4, Block.tnt.blockID);
		world.setBlock(x + 3, y + 1, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y + 1, z + 6, 0);
		world.setBlock(x + 3, y + 2, z, 0);
		world.setBlock(x + 3, y + 2, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y + 2, z + 2, Block.tnt.blockID);
		world.setBlock(x + 3, y + 2, z + 3, Block.tnt.blockID);
		world.setBlock(x + 3, y + 2, z + 4, Block.tnt.blockID);
		world.setBlock(x + 3, y + 2, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y + 2, z + 6, 0);
		world.setBlock(x + 3, y + 3, z, 0);
		world.setBlock(x + 3, y + 3, z + 1, NanotechBlock.nukeBuildingStairs.blockID, 2, 0);
		world.setBlock(x + 3, y + 3, z + 2, Block.tnt.blockID);
		world.setBlock(x + 3, y + 3, z + 3, Block.tnt.blockID);
		world.setBlock(x + 3, y + 3, z + 4, Block.tnt.blockID);
		world.setBlock(x + 3, y + 3, z + 5, NanotechBlock.nukeBuildingStairs.blockID, 3, 0);
		world.setBlock(x + 3, y + 3, z + 6, 0);
		world.setBlock(x + 3, y + 4, z, 0);
		world.setBlock(x + 3, y + 4, z + 1, NanotechBlock.nukeBuildingBlock.blockID, 4, 0);
		world.setBlock(x + 3, y + 4, z + 2, Block.tnt.blockID);
		world.setBlock(x + 3, y + 4, z + 3, Block.tnt.blockID);
		world.setBlock(x + 3, y + 4, z + 4, Block.tnt.blockID);
		world.setBlock(x + 3, y + 4, z + 5, NanotechBlock.nukeBuildingBlock.blockID, 2, 0);
		world.setBlock(x + 3, y + 4, z + 6, 0);
		world.setBlock(x + 3, y + 5, z, 0);
		world.setBlock(x + 3, y + 5, z + 1, 0);
		world.setBlock(x + 3, y + 5, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y + 5, z + 3, Block.tnt.blockID);
		world.setBlock(x + 3, y + 5, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y + 5, z + 5, 0);
		world.setBlock(x + 3, y + 5, z + 6, 0);
		world.setBlock(x + 3, y + 6, z, 0);
		world.setBlock(x + 3, y + 6, z + 1, 0);
		world.setBlock(x + 3, y + 6, z + 2, NanotechBlock.nukeBuildingStairs.blockID, 2, 0);
		world.setBlock(x + 3, y + 6, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y + 6, z + 4, NanotechBlock.nukeBuildingStairs.blockID, 3, 0);
		world.setBlock(x + 3, y + 6, z + 5, 0);
		world.setBlock(x + 3, y + 6, z + 6, 0);
		world.setBlock(x + 3, y + 7, z, 0);
		world.setBlock(x + 3, y + 7, z + 1, 0);
		world.setBlock(x + 3, y + 7, z + 2, 0);
		world.setBlock(x + 3, y + 7, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y + 7, z + 4, 0);
		world.setBlock(x + 3, y + 7, z + 5, 0);
		world.setBlock(x + 3, y + 7, z + 6, 0);
		world.setBlock(x + 3, y + 8, z, 0);
		world.setBlock(x + 3, y + 8, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y + 8, z + 2, NanotechBlock.nukeBuildingStairs.blockID, 3, 0);
		world.setBlock(x + 3, y + 8, z + 3, 0);
		world.setBlock(x + 3, y + 8, z + 4, NanotechBlock.nukeBuildingStairs.blockID, 2, 0);
		world.setBlock(x + 3, y + 8, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 3, y + 8, z + 6, 0);
		world.setBlock(x + 4, y - 4, z, Block.stone.blockID);
		world.setBlock(x + 4, y - 4, z + 1, Block.stone.blockID);
		world.setBlock(x + 4, y - 4, z + 2, Block.stone.blockID);
		world.setBlock(x + 4, y - 4, z + 3, Block.stone.blockID);
		world.setBlock(x + 4, y - 4, z + 4, Block.stone.blockID);
		world.setBlock(x + 4, y - 4, z + 5, Block.stone.blockID);
		world.setBlock(x + 4, y - 4, z + 6, Block.stone.blockID);
		world.setBlock(x + 4, y - 3, z, Block.stone.blockID);
		world.setBlock(x + 4, y - 3, z + 1, Block.stone.blockID);
		world.setBlock(x + 4, y - 3, z + 2, Block.stone.blockID);
		world.setBlock(x + 4, y - 3, z + 3, NanotechBlock.nukeBuildingStairs.blockID, 5, 0);
		world.setBlock(x + 4, y - 3, z + 4, Block.stone.blockID);
		world.setBlock(x + 4, y - 3, z + 5, Block.stone.blockID);
		world.setBlock(x + 4, y - 3, z + 6, Block.stone.blockID);
		world.setBlock(x + 4, y - 2, z, Block.dirt.blockID);
		world.setBlock(x + 4, y - 2, z + 1, Block.dirt.blockID);
		world.setBlock(x + 4, y - 2, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y - 2, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y - 2, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y - 2, z + 5, Block.dirt.blockID);
		world.setBlock(x + 4, y - 2, z + 6, Block.dirt.blockID);
		world.setBlock(x + 4, y - 1, z, Block.dirt.blockID);
		world.setBlock(x + 4, y - 1, z + 1, NanotechBlock.nukeBuildingStairs.blockID, 6, 0);
		world.setBlock(x + 4, y - 1, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y - 1, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y - 1, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y - 1, z + 5, NanotechBlock.nukeBuildingStairs.blockID, 7, 0);
		world.setBlock(x + 4, y - 1, z + 6, Block.dirt.blockID);
		world.setBlock(x + 4, y, z, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 4, y, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y, z + 2, Block.tnt.blockID);
		world.setBlock(x + 4, y, z + 3, Block.tnt.blockID);
		world.setBlock(x + 4, y, z + 4, Block.tnt.blockID);
		world.setBlock(x + 4, y, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y, z + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 4, y + 1, z, 0);
		world.setBlock(x + 4, y + 1, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y + 1, z + 2, Block.tnt.blockID);
		world.setBlock(x + 4, y + 1, z + 3, Block.tnt.blockID);
		world.setBlock(x + 4, y + 1, z + 4, Block.tnt.blockID);
		world.setBlock(x + 4, y + 1, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y + 1, z + 6, 0);
		world.setBlock(x + 4, y + 2, z, 0);
		world.setBlock(x + 4, y + 2, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y + 2, z + 2, Block.tnt.blockID);
		world.setBlock(x + 4, y + 2, z + 3, Block.tnt.blockID);
		world.setBlock(x + 4, y + 2, z + 4, Block.tnt.blockID);
		world.setBlock(x + 4, y + 2, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y + 2, z + 6, 0);
		world.setBlock(x + 4, y + 3, z, 0);
		world.setBlock(x + 4, y + 3, z + 1, NanotechBlock.nukeBuildingStairs.blockID, 2, 0);
		world.setBlock(x + 4, y + 3, z + 2, Block.tnt.blockID);
		world.setBlock(x + 4, y + 3, z + 3, Block.tnt.blockID);
		world.setBlock(x + 4, y + 3, z + 4, Block.tnt.blockID);
		world.setBlock(x + 4, y + 3, z + 5, NanotechBlock.nukeBuildingStairs.blockID, 3, 0);
		world.setBlock(x + 4, y + 3, z + 6, 0);
		world.setBlock(x + 4, y + 4, z, 0);
		world.setBlock(x + 4, y + 4, z + 1, 0);
		world.setBlock(x + 4, y + 4, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y + 4, z + 3, Block.tnt.blockID);
		world.setBlock(x + 4, y + 4, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y + 4, z + 5, 0);
		world.setBlock(x + 4, y + 4, z + 6, 0);
		world.setBlock(x + 4, y + 5, z, 0);
		world.setBlock(x + 4, y + 5, z + 1, 0);
		world.setBlock(x + 4, y + 5, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y + 5, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y + 5, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y + 5, z + 5, 0);
		world.setBlock(x + 4, y + 5, z + 6, 0);
		world.setBlock(x + 4, y + 6, z, 0);
		world.setBlock(x + 4, y + 6, z + 1, 0);
		world.setBlock(x + 4, y + 6, z + 2, 0);
		world.setBlock(x + 4, y + 6, z + 3, NanotechBlock.nukeBuildingStairs.blockID, 1, 0);
		world.setBlock(x + 4, y + 6, z + 4, 0);
		world.setBlock(x + 4, y + 6, z + 5, 0);
		world.setBlock(x + 4, y + 6, z + 6, 0);
		world.setBlock(x + 4, y + 7, z, 0);
		world.setBlock(x + 4, y + 7, z + 1, 0);
		world.setBlock(x + 4, y + 7, z + 2, 0);
		world.setBlock(x + 4, y + 7, z + 3, 0);
		world.setBlock(x + 4, y + 7, z + 4, 0);
		world.setBlock(x + 4, y + 7, z + 5, 0);
		world.setBlock(x + 4, y + 7, z + 6, 0);
		world.setBlock(x + 4, y + 8, z, 0);
		world.setBlock(x + 4, y + 8, z + 1, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y + 8, z + 2, NanotechBlock.nukeBuildingBlock.blockID, 7, 0);
		world.setBlock(x + 4, y + 8, z + 3, NanotechBlock.nukeBuildingStairs.blockID);
		world.setBlock(x + 4, y + 8, z + 4, NanotechBlock.nukeBuildingBlock.blockID, 8, 0);
		world.setBlock(x + 4, y + 8, z + 5, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 4, y + 8, z + 6, 0);
		world.setBlock(x + 5, y - 4, z, Block.stone.blockID);
		world.setBlock(x + 5, y - 4, z + 1, Block.stone.blockID);
		world.setBlock(x + 5, y - 4, z + 2, Block.stone.blockID);
		world.setBlock(x + 5, y - 4, z + 3, Block.stone.blockID);
		world.setBlock(x + 5, y - 4, z + 4, Block.stone.blockID);
		world.setBlock(x + 5, y - 4, z + 5, Block.stone.blockID);
		world.setBlock(x + 5, y - 4, z + 6, Block.stone.blockID);
		world.setBlock(x + 5, y - 3, z, Block.stone.blockID);
		world.setBlock(x + 5, y - 3, z + 1, Block.stone.blockID);
		world.setBlock(x + 5, y - 3, z + 2, Block.stone.blockID);
		world.setBlock(x + 5, y - 3, z + 3, Block.stone.blockID);
		world.setBlock(x + 5, y - 3, z + 4, Block.stone.blockID);
		world.setBlock(x + 5, y - 3, z + 5, Block.stone.blockID);
		world.setBlock(x + 5, y - 3, z + 6, Block.stone.blockID);
		world.setBlock(x + 5, y - 2, z, Block.dirt.blockID);
		world.setBlock(x + 5, y - 2, z + 1, Block.dirt.blockID);
		world.setBlock(x + 5, y - 2, z + 2, Block.dirt.blockID);
		world.setBlock(x + 5, y - 2, z + 3, Block.dirt.blockID);
		world.setBlock(x + 5, y - 2, z + 4, Block.dirt.blockID);
		world.setBlock(x + 5, y - 2, z + 5, Block.dirt.blockID);
		world.setBlock(x + 5, y - 2, z + 6, Block.dirt.blockID);
		world.setBlock(x + 5, y - 1, z, Block.dirt.blockID);
		world.setBlock(x + 5, y - 1, z + 1, Block.dirt.blockID);
		world.setBlock(x + 5, y - 1, z + 2, NanotechBlock.nukeBuildingStairs.blockID, 5, 0);
		world.setBlock(x + 5, y - 1, z + 3, NanotechBlock.nukeBuildingStairs.blockID, 5, 0);
		world.setBlock(x + 5, y - 1, z + 4, NanotechBlock.nukeBuildingStairs.blockID, 5, 0);
		world.setBlock(x + 5, y - 1, z + 5, Block.dirt.blockID);
		world.setBlock(x + 5, y - 1, z + 6, Block.dirt.blockID);
		world.setBlock(x + 5, y, z, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 5, y, z + 1, NanotechBlock.nukeBuildingBlock.blockID, 6, 0);
		world.setBlock(x + 5, y, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y, z + 5, NanotechBlock.nukeBuildingBlock.blockID, 5, 0);
		world.setBlock(x + 5, y, z + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 5, y + 1, z, 0);
		world.setBlock(x + 5, y + 1, z + 1, NanotechBlock.nukeBuildingBlock.blockID, 6, 0);
		world.setBlock(x + 5, y + 1, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y + 1, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y + 1, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y + 1, z + 5, NanotechBlock.nukeBuildingBlock.blockID, 5, 0);
		world.setBlock(x + 5, y + 1, z + 6, 0);
		world.setBlock(x + 5, y + 2, z, 0);
		world.setBlock(x + 5, y + 2, z + 1, NanotechBlock.nukeBuildingBlock.blockID, 6, 0);
		world.setBlock(x + 5, y + 2, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y + 2, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y + 2, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y + 2, z + 5, NanotechBlock.nukeBuildingBlock.blockID, 5, 0);
		world.setBlock(x + 5, y + 2, z + 6, 0);
		world.setBlock(x + 5, y + 3, z, 0);
		world.setBlock(x + 5, y + 3, z + 1, 0);
		world.setBlock(x + 5, y + 3, z + 2, NanotechBlock.nukeBuildingStairs.blockID, 1, 0);
		world.setBlock(x + 5, y + 3, z + 3, NanotechBlock.nukeBuildingStairs.blockID, 1, 0);
		world.setBlock(x + 5, y + 3, z + 4, NanotechBlock.nukeBuildingStairs.blockID, 1, 0);
		world.setBlock(x + 5, y + 3, z + 5, 0);
		world.setBlock(x + 5, y + 3, z + 6, 0);
		world.setBlock(x + 5, y + 4, z, 0);
		world.setBlock(x + 5, y + 4, z + 1, 0);
		world.setBlock(x + 5, y + 4, z + 2, 0);
		world.setBlock(x + 5, y + 4, z + 3, NanotechBlock.nukeBuildingBlock.blockID, 1, 0);
		world.setBlock(x + 5, y + 4, z + 4, 0);
		world.setBlock(x + 5, y + 4, z + 5, 0);
		world.setBlock(x + 5, y + 4, z + 6, 0);
		world.setBlock(x + 5, y + 5, z, 0);
		world.setBlock(x + 5, y + 5, z + 1, 0);
		world.setBlock(x + 5, y + 5, z + 2, 0);
		world.setBlock(x + 5, y + 5, z + 3, 0);
		world.setBlock(x + 5, y + 5, z + 4, 0);
		world.setBlock(x + 5, y + 5, z + 5, 0);
		world.setBlock(x + 5, y + 5, z + 6, 0);
		world.setBlock(x + 5, y + 6, z, 0);
		world.setBlock(x + 5, y + 6, z + 1, 0);
		world.setBlock(x + 5, y + 6, z + 2, 0);
		world.setBlock(x + 5, y + 6, z + 3, 0);
		world.setBlock(x + 5, y + 6, z + 4, 0);
		world.setBlock(x + 5, y + 6, z + 5, 0);
		world.setBlock(x + 5, y + 6, z + 6, 0);
		world.setBlock(x + 5, y + 7, z, 0);
		world.setBlock(x + 5, y + 7, z + 1, 0);
		world.setBlock(x + 5, y + 7, z + 2, 0);
		world.setBlock(x + 5, y + 7, z + 3, 0);
		world.setBlock(x + 5, y + 7, z + 4, 0);
		world.setBlock(x + 5, y + 7, z + 5, 0);
		world.setBlock(x + 5, y + 7, z + 6, 0);
		world.setBlock(x + 5, y + 8, z, 0);
		world.setBlock(x + 5, y + 8, z + 1, NanotechBlock.nukeBuildingBlock.blockID, 6, 0);
		world.setBlock(x + 5, y + 8, z + 2, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y + 8, z + 3, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y + 8, z + 4, NanotechBlock.nukeBuildingBlock.blockID);
		world.setBlock(x + 5, y + 8, z + 5, NanotechBlock.nukeBuildingBlock.blockID, 5, 0);
		world.setBlock(x + 5, y + 8, z + 6, 0);
		world.setBlock(x + 6, y - 4, z, Block.stone.blockID);
		world.setBlock(x + 6, y - 4, z + 1, Block.stone.blockID);
		world.setBlock(x + 6, y - 4, z + 2, Block.stone.blockID);
		world.setBlock(x + 6, y - 4, z + 3, Block.stone.blockID);
		world.setBlock(x + 6, y - 4, z + 4, Block.stone.blockID);
		world.setBlock(x + 6, y - 4, z + 5, Block.stone.blockID);
		world.setBlock(x + 6, y - 4, z + 6, Block.stone.blockID);
		world.setBlock(x + 6, y - 3, z, Block.stone.blockID);
		world.setBlock(x + 6, y - 3, z + 1, Block.stone.blockID);
		world.setBlock(x + 6, y - 3, z + 2, Block.stone.blockID);
		world.setBlock(x + 6, y - 3, z + 3, Block.stone.blockID);
		world.setBlock(x + 6, y - 3, z + 4, Block.stone.blockID);
		world.setBlock(x + 6, y - 3, z + 5, Block.stone.blockID);
		world.setBlock(x + 6, y - 3, z + 6, Block.stone.blockID);
		world.setBlock(x + 6, y - 2, z, Block.dirt.blockID);
		world.setBlock(x + 6, y - 2, z + 1, Block.dirt.blockID);
		world.setBlock(x + 6, y - 2, z + 2, Block.dirt.blockID);
		world.setBlock(x + 6, y - 2, z + 3, Block.dirt.blockID);
		world.setBlock(x + 6, y - 2, z + 4, Block.dirt.blockID);
		world.setBlock(x + 6, y - 2, z + 5, Block.dirt.blockID);
		world.setBlock(x + 6, y - 2, z + 6, Block.dirt.blockID);
		world.setBlock(x + 6, y - 1, z, Block.dirt.blockID);
		world.setBlock(x + 6, y - 1, z + 1, Block.dirt.blockID);
		world.setBlock(x + 6, y - 1, z + 2, Block.dirt.blockID);
		world.setBlock(x + 6, y - 1, z + 3, Block.dirt.blockID);
		world.setBlock(x + 6, y - 1, z + 4, Block.dirt.blockID);
		world.setBlock(x + 6, y - 1, z + 5, Block.dirt.blockID);
		world.setBlock(x + 6, y - 1, z + 6, Block.dirt.blockID);
		world.setBlock(x + 6, y, z, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 6, y, z + 1, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 6, y, z + 2, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 6, y, z + 3, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 6, y, z + 4, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 6, y, z + 5, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 6, y, z + 6, NanotechBlock.nanoGrass.blockID);
		world.setBlock(x + 6, y + 1, z, 0);
		world.setBlock(x + 6, y + 1, z + 1, 0);
		world.setBlock(x + 6, y + 1, z + 2, 0);
		world.setBlock(x + 6, y + 1, z + 3, 0);
		world.setBlock(x + 6, y + 1, z + 4, 0);
		world.setBlock(x + 6, y + 1, z + 5, 0);
		world.setBlock(x + 6, y + 1, z + 6, 0);
		world.setBlock(x + 6, y + 2, z, 0);
		world.setBlock(x + 6, y + 2, z + 1, 0);
		world.setBlock(x + 6, y + 2, z + 2, 0);
		world.setBlock(x + 6, y + 2, z + 3, 0);
		world.setBlock(x + 6, y + 2, z + 4, 0);
		world.setBlock(x + 6, y + 2, z + 5, 0);
		world.setBlock(x + 6, y + 2, z + 6, 0);
		world.setBlock(x + 6, y + 3, z, 0);
		world.setBlock(x + 6, y + 3, z + 1, 0);
		world.setBlock(x + 6, y + 3, z + 2, 0);
		world.setBlock(x + 6, y + 3, z + 3, 0);
		world.setBlock(x + 6, y + 3, z + 4, 0);
		world.setBlock(x + 6, y + 3, z + 5, 0);
		world.setBlock(x + 6, y + 3, z + 6, 0);
		world.setBlock(x + 6, y + 4, z, 0);
		world.setBlock(x + 6, y + 4, z + 1, 0);
		world.setBlock(x + 6, y + 4, z + 2, 0);
		world.setBlock(x + 6, y + 4, z + 3, 0);
		world.setBlock(x + 6, y + 4, z + 4, 0);
		world.setBlock(x + 6, y + 4, z + 5, 0);
		world.setBlock(x + 6, y + 4, z + 6, 0);
		world.setBlock(x + 6, y + 5, z, 0);
		world.setBlock(x + 6, y + 5, z + 1, 0);
		world.setBlock(x + 6, y + 5, z + 2, 0);
		world.setBlock(x + 6, y + 5, z + 3, 0);
		world.setBlock(x + 6, y + 5, z + 4, 0);
		world.setBlock(x + 6, y + 5, z + 5, 0);
		world.setBlock(x + 6, y + 5, z + 6, 0);
		world.setBlock(x + 6, y + 6, z, 0);
		world.setBlock(x + 6, y + 6, z + 1, 0);
		world.setBlock(x + 6, y + 6, z + 2, 0);
		world.setBlock(x + 6, y + 6, z + 3, 0);
		world.setBlock(x + 6, y + 6, z + 4, 0);
		world.setBlock(x + 6, y + 6, z + 5, 0);
		world.setBlock(x + 6, y + 6, z + 6, 0);
		world.setBlock(x + 6, y + 7, z, 0);
		world.setBlock(x + 6, y + 7, z + 1, 0);
		world.setBlock(x + 6, y + 7, z + 2, 0);
		world.setBlock(x + 6, y + 7, z + 3, 0);
		world.setBlock(x + 6, y + 7, z + 4, 0);
		world.setBlock(x + 6, y + 7, z + 5, 0);
		world.setBlock(x + 6, y + 7, z + 6, 0);
		world.setBlock(x + 6, y + 8, z, 0);
		world.setBlock(x + 6, y + 8, z + 1, 0);
		world.setBlock(x + 6, y + 8, z + 2, 0);
		world.setBlock(x + 6, y + 8, z + 3, 0);
		world.setBlock(x + 6, y + 8, z + 4, 0);
		world.setBlock(x + 6, y + 8, z + 5, 0);
		world.setBlock(x + 6, y + 8, z + 6, 0);
		world.setBlock(x + 3, y - 2, z + 3, NanotechBlock.nukeBuildingBlock.blockID, 9, 0);
		return true;
	}
}